### ISSUE TITLE
Rhythm Heaven Remix Editor Version 3

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor#183]
## Description
We have reached a point in the Rhythm Heaven Remix Editor's life where it is time for change.

The jump from RHRE0 to RHRE2 was massive. It brought new features such as multiple tempo changes, a cleaner pattern selector, music volume, and more. But after over 54 releases later, issues pile up and code gets spaghettified.

I present the rough plan for **Rhythm Heaven Remix Editor v3.0.0**. This will be a large undertaking and will take significantly longer than an average update to complete.

## Objectives
* To **clean up** the internal codebase
* To allow for more features that should've been in RHRE2 from the beginning
* To reduce update sizes by separating the sound database

## Goals
* Completely rewritten from the ground-up
* Git-based sound database which can be **patched** separately from editor updates
  * Fully lazy loaded
* Cleaning up the variation types (example: languages, remix-specific cues) in games
* Reducing cue duplication (see point above)
* Better call-and-response game support (Working Dough, First Contact, etc style games)
* Better keep-the-beat game support (Bunny Hop, Lockstep, Sumo Bros., etc)
* Better stretchable pattern support (Bouncy Road, Clappy Trio)
  * See issue #179 
  * Now called "equidistant" objects
* Improved file types
  * Specifically the introduction of a single, unified file type called `rhre3`
    * Standard ZIP format (identical to brhre2's internal format)
    * All metadata such as autosave-state, music, *maybe* custom sounds (pending)
* Proper upscaling support (still 16:9)
* Removal of Lua scripting because no one used it + annoying upkeep

## What about RHRE2?
* Updates for RHRE2 will slow significantly or stop to accommodate this new workload
  * The last minor (non-patch) update will be `v2.17.0`

*Prerequisites omitted for brevity. Plan not final and subject to heavy change (which will be updated here as necessary).*

**Comment by RhythmChan64** [comment]
In 3.0.0. or future releases...Will there be an EXE version?

**Comment by chrislo27** [comment]
No. I refuse to be platform specific.

**Comment by HyenaGuy12** [comment]
pirate crew is a little buggy

**Comment by SukateesHatesLife** [comment]
it may be my computer but when i try to change tempo. it will not work. i tried the arrow keys. i even made sure that the wheel even works and sure enough it does. am i doing something wrong?

**Comment by chrislo27** [comment]
This is the wrong issue to post in. Please check for previous issues before posting.

https://github.com/chrislo27/RhythmHeavenRemixEditor/issues/209
