### ISSUE TITLE
Graphics drivers incompatible error

### ISSUE THREAD

**Issue by Aleksi12345** [chrislo27/RhythmHeavenRemixEditor#185]
### Prerequisites
* This issue specifically has something to do with RHRE2
* I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [ * ] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
the program wont start when i open it. everything seems normal but then it will write about badlogic and opengl not being supported by video drivers

### Steps to Reproduce the Problem
1. i dont know
2. i dont know

### Stacktrace/error log
[cmd text.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1225113/cmd.text.txt)

**Expected behavior:** the program should run normally

**Actual behavior:** the cmd writes things about badlogic and opengl not being supported by video drivers

**Version affected:** v2.17

### Additional Information
when it gets to the "press any button" part it just closes itself

**Comment by chrislo27** [comment]
Update your graphics drivers. If that doesn't work, it is possible your graphics card/integrated card cannot run OpenGL 2.X+ (which is fairly rare nowadays, most even support up to OpenGL 4).

Could you note down what graphics card you have? It may be integrated (like Intel HD Graphics).

**Comment by chrislo27** [comment]
Please try this as well: go into command prompt (hold shift and right click File Explorer while in the folder that contains RHRE.jar, select open command prompt here), type in `java -jar RHRE.jar -softwaremode 1` and execute.

**Comment by chrislo27** [comment]
This issue will be closed because of the following reason(s):
  * Inactivity
