### ISSUE TITLE
Sound on Lockstep (Megamix) onbeat - 1

### ISSUE THREAD

**Issue by rhythmheavenlover12** [chrislo27/RhythmHeavenRemixEditor#190]
### Prerequisites
* [ ] This issue specifically has something to do with RHRE3
* [ ] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [ ] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [ ] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed
* [ ] I have searched the diff from master to dev checking if this issue was already fixed

### Description
[insert description of the issue/suggestion]

### Steps to Reproduce the Problem
[you can remove everything past the description if this isn't a bug/issue]
1. [First step]
2. [Second step]

### Stacktrace/error log
[Attach the log file from `logs/log_YYYY-MM-DD_HH-MM-SS.txt here because it contains important system information]

**Expected behavior:** [insert what was supposed to happen here]

**Actual behavior:** [insert what actually happened here]

**Version affected:** [insert the version of RHRE3 here]

### Additional Information
[optional: insert any other information that may be able to help me with the problem here]

**Comment by chrislo27** [comment]
This issue will be **permanently** closed because of the following reason(s):
* The template was removed, or filled out incorrectly
