### ISSUE TITLE
Subsequent Air Rally "Ba bum bum bum" Cues At Different Distances

### ISSUE THREAD

**Issue by iRonnoc5** [chrislo27/RhythmHeavenRemixEditor#192]
### Prerequisites
* [x] This issue specifically has something to do with RHRE3
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed
* [x] I have searched [the diff from master to dev](https://github.com/chrislo27/RhythmHeavenRemixEditor/compare/master...dev) checking if this issue was already fixed

### Description

There's no subsequent cues for "ba bum bum bum," excluding the one at the closest distance. Adding subsequent cues for the far, farther, and further would make things sound much nicer if someone intends to do multiple "ba bum bum bum" cues in a row.

**Comment by chrislo27** [comment]
I am not sure if the SFX for these cues are available. F Yeah, Rhythm Heaven!'s Tumblr page does not have them, so this issue may be standing for a while.

**Comment by chrislo27** [comment]
As of [SFX Database v64](https://github.com/chrislo27/RHRE-database/releases/tag/v64), this has been resolved.
