### ISSUE TITLE
Open GL 1.0 Support Idea

### ISSUE THREAD

**Issue by pakiefromthebag** [chrislo27/RhythmHeavenRemixEditor#194]
**Idea**  
My PC Has Open GL 1.0 
And My Pc Won't Run 
The Editor.
So. Add Support For 
Open GL 1.0.
Simple.

**Comment by chrislo27** [comment]
This issue will be **indefinitely** closed because of the following reason(s):
* The template was removed, or filled out incorrectly
* LibGDX only supports OpenGL 2.0+, so please bring this up with *them*

**Comment by pakiefromthebag** [comment]
Oh. Ok. I Will  Contact Them.
