### ISSUE TITLE
New Shake function will continue indefinitely if playback is paused in the middle of it.

### ISSUE THREAD

**Issue by Mixelz** [chrislo27/RhythmHeavenRemixEditor#195]
### Prerequisites
* [x] This issue specifically has something to do with RHRE3
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed
* [x] I have searched [the diff from master to dev](https://github.com/chrislo27/RhythmHeavenRemixEditor/compare/master...dev) checking if this issue was already fixed

### Description
When using the newly implemented shake function, pausing play back in the middle of a shake causes the shake to persist until you manually go back to it and go through the entire shake,

### Steps to Reproduce the Problem
1. Put a shake function in the track.
2. While in the middle of it, pause playback.
3. Resume playback in a different section.
4. Shaking will continue.
5. To end the shaking, go back to the initial shake function and play through it.

### Stacktrace/error log
[log_2017-09-21_23-44-20.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1323511/log_2017-09-21_23-44-20.txt)

**Expected behavior:** No shaking when pausing playback and resuming elsewhere

**Actual behavior:** Shaking.

**Version affected:** 3.2.0

**Comment by chrislo27** [comment]
I will investigate this shortly. Do you know if this also happens with subtitles (code is similar)?

**Comment by Mixelz** [comment]
It does not happen with subtitles, just checked.

**Comment by chrislo27** [comment]
This issue has been fixed and v3.2.1 should be released in the next hour. Thank you for your report!

(By the way, it's really appreciated when you filled out the template correctly. Lately I have been getting a lot of bogus reports so this is a sight for sore eyes. :smile:)

**Comment by Mixelz** [comment]
Mhm, hard to pin down an issue with something when the most you're getting is vauge descriptions of what it even is. 😃

**Comment by chrislo27** [comment]
This issue will be **indefinitely** closed because of the following reason(s):
  * This has been fixed in [v3.2.1](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.2.1)
