### ISSUE TITLE
A separate bar for special entities (e.g. Subtitles, Shake, etc.) - i.e.: Ledger Lines

### ISSUE THREAD

**Issue by Mixelz** [chrislo27/RhythmHeavenRemixEditor#196]
### Prerequisites
* [x] This issue specifically has something to do with RHRE3
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed
* [x] I have searched [the diff from master to dev](https://github.com/chrislo27/RhythmHeavenRemixEditor/compare/master...dev) checking if this issue was already fixed

### Description
With the hope that we'll be getting even more of these special effects in the near future, I feel that it would be reasonable to ask for a seperate bar to hold these special effects in. As it stands you have to dedicate the bottom bar to these effects, and you can very easily run into a situation where you have to choose between having the song subtitled, using one of the effects, or in a rare case be unable to do either. (Board Meeting for example requires that you use up at least 4 bars if your not just using the together cue).

I suspect this would only be a feature worth putting time into when we have more than the few effects we have now, but it wouldn't hurt to at least get it on the board as a feature worth implementing in the future! 😄

**Comment by chrislo27** [comment]
The concept of [ledger lines](https://en.wikipedia.org/wiki/Ledger_line) interests me greatly, and the special entities would fit right into this scenario. I like it! I'll consider working on it during the weekend.

**Comment by chrislo27** [comment]
https://i.imgur.com/Ju4kti4.gifv
