### ISSUE TITLE
Feature Request: Some ideas for special effects (7 in total)

### ISSUE THREAD

**Issue by Mixelz** [chrislo27/RhythmHeavenRemixEditor#198]
### Description
As the title says, these are simply just ideas for possible special effects. I want to preface this by saying that **I do not know how to code.** For all I know all of these ideas could be impossible given whatever limitations may be in place. Regardless, I simply wanted to share these ideas in the hopes that the special effects section could expand a far ways beyond what it currently is.
With that being said:

1. Bounce - Bouncing the screen to the beat of the song, maybe a simple block that makes the screen bounce, would allow for off-beat bouncing or a switch from off to on ala lockstep.

2. Change Palette - Changes the current palette to another defined palette, could signify a change in tone of the song or maybe just for when the beat drops. 😛 

3. Squeeze - Streches/ Squeezes the screen by a set amount, could be implemented as the shake is now. Going down an octave to stretch the screen and up to squeeze it. Could be used for more impact during long notes or stingers.

4. Rotate - Would rotate the screen however many degrees set, could be done same as shake is now only with rotational degrees. Could be used as a controlled shake as well depending on how it's done.

5. Font/Text Color change - To be used along side subtitles to denote perhaps a difference in whos speaking, may be better deligated as a setting instead of an entire effect.

6. Refrain - As it does in sheet music, this would allow for certain sections to be repeated, most likely the chorus. It would not only make the editor feel more like an actual bit of sheet music, as the addition of the End Remix function does, but allow for the length of a remix to be cut down as you could simply repeat instead of copying/pasting an entire section.

7. Misc. - I remember that in an older version there was the ability to do custom LUA for whatever needs would need to be suited for the remixers. This could be way to re-introduce that idea, only instead with custom made effects.

If none of these work then I hope at least this will faciliate other great ideas to spring forward! 😄

**Comment by chrislo27** [comment]
I would love to discuss this more with you right now! Do you have a Discord account? There's a Rhythm Heaven Discord server I frequent and have a RHRE channel on. 

Here's an invite link: https://discord.gg/Bm2K8Ad

It would make this a lot more streamlined and easier to discuss.

**Comment by chrislo27** [comment]
Considered special effects: Bounce, Rotate
Already implemented: Text colour change
Thinking: Squeeze, Change Theme
Won't do: scripting, refrain
