### ISSUE TITLE
Can I have some help here?

### ISSUE THREAD

**Issue by LizBAP64** [chrislo27/RhythmHeavenRemixEditor#202]
Hi, I have Java 1.8, and just downloaded RHRE, but it just won't open. Can I have some on how to run RHRE so I can make some remixes?

**Comment by PriffyViole** [comment]
You also need a specific version of OpenGL. If you don't have it, it won't run. Sorry :(

**Comment by chrislo27** [comment]
Please do not remove the issue template. It is there for a reason so I can gather information without asking too many questions.

Please upload a log file. You can find them in the neighboring logs folder. Alternatively, screenshot the terminal.

**Comment by LizBAP64** [comment]
![image](https://user-images.githubusercontent.com/32303878/30909699-1cded9b2-a350-11e7-87b9-3f33da626b50.png)
Here, I took a screenshot! And where can I download this version of OpenGL?

**Comment by chrislo27** [comment]
Install Java. You'll know you'll have it if you go into command prompt and enter `java -version`.

No, it's not installed. That's what the error message says.

**Comment by LizBAP64** [comment]
I did install it.
![image](https://user-images.githubusercontent.com/32303878/30942136-13c8060c-a3b7-11e7-9701-4f01d3d9a6b9.png)

**Comment by chrislo27** [comment]
And did you google the error message? What results did you get?

I'm asking questions like these to improve self-sufficiency with errors.

**Comment by LizBAP64** [comment]
How do I do that???

**Comment by LizBAP64** [comment]
Add java to the environment path, I mean.

**Comment by LizBAP64** [comment]
Make it quick and simple, please... :smile:

**Comment by LizBAP64** [comment]
![image](https://user-images.githubusercontent.com/32303878/30995846-ae44f6a8-a48a-11e7-986d-0ee627577e94.png)
Another screenshot, sorry but I just wanna make remixes so badly... :worried:

**Comment by chrislo27** [comment]
Looks like it's on the environment path now. Go back to the RHRE folder (wherever you downloaded it to) and run the bat file. You should be set.

Please do not:
a) Make multiple comments where they could be combined into one
b) Beg/plead
c) Attempt to guilt trip me

It is not appreciated.

**Comment by LizBAP64** [comment]
Sorry.
