### ISSUE TITLE
Can't use a long music file

### ISSUE THREAD

**Issue by McCake147** [chrislo27/RhythmHeavenRemixEditor#204]
### Information
**Log file**: [log_2017-09-30_13-15-35.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1346664/log_2017-09-30_13-15-35.txt)

**Editor version**: v3.3.0

### Description
I'm trying to use a particular song for a remix that is 27 minutes long, and when trying to select it I get an error saying: "FAILED TO LOAD: The music file is invalid. Try again or return to the editor. java.lang.OutOfMemoryError" I have tried converting the file to a .wav file (previously I was using an mp3) and the problem persists. If there is no fix for this, I could always try splitting the song into smaller parts and editing them together.

**Comment by chrislo27** [comment]
As songs are loaded into memory now as of v3.3.0, a new requirement is that you have enough memory to load the entire song.

The amount of minimum memory allocated to the Java Virtual Machine is generally 50 MB + the size of the sound file. If a **quarter** of your installed RAM does not meet this requirement, you will have to manually allocate it. It seems you have only allocated 256 MB of memory to the JVM.

Either in Command Prompt or by editing the batch file, add the JVM flag `-Xmx#m`, where # is the number of megabytes of RAM to allocate.

```
java -jar -Xmx1024m RHRE3.jar
```
would allocate 1024 MB (or 1 GB) of heap space to the Java Virtual Machine.

There is no way to reduce this requirement. You are working with an audio editor and it is expected you have the requirements to mass-edit audio.

I may improve the error message by v3.4.0.

**Comment by McCake147** [comment]
Thanks for the fix, can't wait to try and work with Gigamix!
Also, I agree that you shouldn't put too much work into fixing this, especially since now people can look up the problem and find this thread.

**Comment by chrislo27** [comment]
Please report back if whatever I suggested works or not (I wrote a documentation page but I need to make sure it's valid). I decided to do the special error messages for excessively large files, haha!

The theoretical upper limit is something insane like 6 hours 45 minutes so I think we're good (you would need virtually 3 gigabytes of memory allocated just for RHRE3 at that point).
