### ISSUE TITLE
No Japanese Cheer Readers

### ISSUE THREAD

**Issue by DarkerBit** [chrislo27/RhythmHeavenRemixEditor#205]
**As of DB version**: v13

There don't seem to be any Japanese Cheer Readers sounds, and as thus I had to use the English one, which doesn't fit in with the rest of my Japanese sounds.

I would have posted this on your Games Database issues page, if it had one.

(Actually, mind making one? It seems quite a lot of the issues are with the SFX database are posted on here, and I think they should belong on the repository designated for it.)

**Comment by chrislo27** [comment]
Japanese SFX for Cheer Readers as accurate as the current English version is currently impossible to obtain (not to mention having to wait for someone to database it). This issue may not be resolved for a long time.

**Comment by DarkerBit** [comment]
Ah, thanks anyway :)

14.10.2017 2.07 "chrislo27" <notifications@github.com> kirjoitti:

**Comment by Miracle22s** [comment]
I might as well database Cheer Readers Japanese myself or wait for someone to do it.

**Comment by chrislo27** [comment]
As of SFX database v61 (and editor version v3.12.2), Cheer Readers (Japanese) has been added. Many thanks to Lvl100Feraligatr for composing this.
