### ISSUE TITLE
CTRL-ALT dragging for call-and-response doesn't work on Mac

### ISSUE THREAD

**Issue by eggman199** [chrislo27/RhythmHeavenRemixEditor#206]
### Information
**Editor version**: 3.4.0

### Description
Instead of creating clones of the response objects, ctrl-alt clicking does nothing. The cues just stay there. Holding any other key with the alt key produces a regular clone.

### Behaviours
**Expected behaviour**: Call-and-response games like Rhythm Tweezers would produce the appropriate picking cues for an appear cue

**Actual behaviour**: Nothing, not even being dragged

**Comment by chrislo27** [comment]
Use a USB keyboard.

**Comment by chrislo27** [comment]
More info is required. Does control on its own work (scrolling trackers)? It seems that alt on its own works.

Does the command key work? You can't just say "every other key" and expect me to know what you pressed.
