### ISSUE TITLE
Fatal Crash upon launch, happens every time

### ISSUE THREAD

**Issue by Mixelz** [chrislo27/RhythmHeavenRemixEditor#208]
### Information
**Log file**: [log_2017-10-29_04-51-26.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1424922/log_2017-10-29_04-51-26.txt)

**Editor version**: 3.4.1

### Description
Upon trying to launch the editor, it just crashes.
There's honestly nothing more to this, I've tried launching exactly a dozen times now and it crashes every single time.
### Behaviours
**Expected behaviour**: The editor to not crash upon launch.

**Actual behaviour**: The editor crashes upon launch

**Comment by patbsomethingidk** [comment]
I'm having that exact problem.

**Comment by FroggyGames** [comment]
same
here's the log: [log_2017-10-29_15-34-49.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1425450/log_2017-10-29_15-34-49.txt)
