### ISSUE TITLE
Unable to change BPM.

### ISSUE THREAD

**Issue by patbsomethingidk** [chrislo27/RhythmHeavenRemixEditor#209]
### Information
**Log file**: [log_2017-10-31_13-58-10.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1432624/log_2017-10-31_13-58-10.txt)

**Editor version**: 3.5.0
### Description
Unable to use scroll wheel, arrow keys, or W and S keys to change BPM.
It's not just BPM, but everything usually changeable by the scroll wheel.

### Behaviours
**Expected behaviour**: Scroll wheel changes BPM.

**Actual behaviour**: Scroll wheel doesn't change BPM.

**Comment by chrislo27** [comment]
Redownload the editor.

Certain old versions have this issue before I reuploaded the release.
