### ISSUE TITLE
More Rockers SFX?

### ISSUE THREAD

**Issue by Domino054** [chrislo27/RhythmHeavenRemixEditor#210]
### Information
**Editor version**: 3.5.0

### Description
Taking a look at the Rockers SFX in the editor, most of them are from when the right guitarist plays. I wonder if you can do the SFX for when the left guitarist plays (I.E. before the guitarists play the final riff and the final riff itself)?

### Behaviours
**Expected behaviour**: The Rockers SFX should have both the left and right guitarists.

**Actual behaviour**: The Rockers SFX are mostly from the right guitarist only.

**Comment by chrislo27** [comment]
As of SFX database release [v23](https://github.com/chrislo27/RHRE-database/releases/tag/v23) a lot of new Rockers sounds have been added.
