### ISSUE TITLE
Music Volume Beyond 100%/Change Volume of Specific Cues

### ISSUE THREAD

**Issue by iRonnoc5** [chrislo27/RhythmHeavenRemixEditor#212]
### Information
**Editor version**: v. 3.5.0

### Description
Sometimes, the cues end up being too loud in comparison to the music, making the music difficult, or sometimes even impossible to hear. A good way to counter this would either be the option to change the volume of selected cues to make them quieter, or to allow the Music Volume option to go beyond 100% and make the music louder for balance.

**Comment by chrislo27** [comment]
This has been resolved as of commit https://github.com/chrislo27/RhythmHeavenRemixEditor/commit/58dc0c230d262f3046a3e824d2a125db508771d6. In the next version (probably v3.6.0) you will be able to increase the music volume up to 200%.

**Comment by frosty-boy** [comment]
a better option would be the ability to change the cues volume, but thus is good for now

**Comment by chrislo27** [comment]
Make your music quieter and edit it in post.

Excessive noise leads to peaking and clipping in the final result.

**Comment by frosty-boy** [comment]
as in, turning down cue volume, not up

**Comment by chrislo27** [comment]
That doesn't change anything. You can still make your music quieter and edit it in post. The cue volumes are already normalized so they will not have to change, only the music does.
