### ISSUE TITLE
Won't open?

### ISSUE THREAD

**Issue by kukiie** [chrislo27/RhythmHeavenRemixEditor#215]
This probably will be a dumb question and all, but it won't open for me. I'm on the latest version.

**Comment by chrislo27** [comment]
State the version you have. Sorry, but I cannot **read your mind** and know what "latest" means for you.

You should also provide all error logs and if none are present screenshots of the console.

Failure to present these crucial pieces of evidence will have your issue closed permanently.

**Comment by kukiie** [comment]
Should've explained better. I have version v3.5.1, and it at first opens, but shortly after it just....closes. I'm not quick enough to take any screenshots.

**Comment by DeckOfNoobs** [comment]
Are you running the .bat file?

**Comment by chrislo27** [comment]
The batch file (or shell file on Unix-like systems) has a console. It provides important information and will hang around even after a crash. You should upload screenshots of its results after the supposed crash.

Keep in mind that this program does have some requirements: at least Java 8 installed, and the necessary drivers to use OpenGL 2.0 or higher.
