### ISSUE TITLE
The editor won't open

### ISSUE THREAD

**Issue by nozomisugiura97** [chrislo27/RhythmHeavenRemixEditor#220]
### Information
**Log file**: [log_2017-12-10_14-44-28.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1545372/log_2017-12-10_14-44-28.txt)

**Editor version**: 3.6.3

### Description
I can't seem to open the editor. A few months back I can still open it.

### Behaviours
**Expected behaviour**: It should open, loading every game mode without issues.

**Actual behaviour**: The SFX Database Update says the following:
**Checking for a new version...**
**0/0**
**0 task(s) completed**
**An error occurred while trying to connect to the Git database. Do you have an Internet connection?**
**You CANNOT use the editor because it is missing files**

**Comment by chrislo27** [comment]
You are missing the most important piece of the template. Please edit your post with the log file attached -- I cannot do anything until I have that.

**Comment by nozomisugiura97** [comment]
Where can I find the log file?

**Comment by chrislo27** [comment]
Look in the sibling `logs` folder next to the jar file. You should take the one with the correct timestamp based on when you launched the program.

**Comment by nozomisugiura97** [comment]
I edited my post with the log file. Hoping this would be fixed :D

**Comment by chrislo27** [comment]
There are numerous potential issues that could lead to these errors. I would suggest that the most probable one is your firewall blocking packets being in and out. Specifically the ports `443` for HTTPS, and `9418` for git-related traffic should be opened.

**Comment by nozomisugiura97** [comment]
Where and how can I open said ports?

**Comment by chrislo27** [comment]
That's dependent on your firewall. I would recommend looking at Windows Firewall because you use Windows. 

If when initially starting the editor you blocked connections for Java (there would've been a dialog box) then no connections would be allowed. This program requires Internet access.
