### ISSUE TITLE
Selector won't open (Mac)

### ISSUE THREAD

**Issue by thatactualdude** [chrislo27/RhythmHeavenRemixEditor#221]
[log_2017-12-12_19-53-03.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1554104/log_2017-12-12_19-53-03.txt)

3.6.3

On the latest version on Mac, the selector won't even open at all. 

When I clicked music, I expected a selector to come up.

What actually happened is that the editor froze for a split second but nothing came up.

**Comment by chrislo27** [comment]
Not enough detail. Did you actually check behind the window in case it appeared there?

Your log file is either wrong or the way it is. There is no other information in the logs that says anything related to what you've described.

Also, next time please follow the issue template. I don't want to spend time decoding sentences; I want to see information where I laid it out.

**Comment by thatactualdude** [comment]
@chrislo27 I couldn't look behind the window, when I tried to press the button to do so.

**Comment by chrislo27** [comment]
This issue will be **indefinitely** closed because of the following reason(s):
 * The author has said to revise it in the future (please open a new separate issue that is complete)
