### ISSUE TITLE
Rhythm Heaven Remix Editor Not Booting

### ISSUE THREAD

**Issue by eridanusofwind** [chrislo27/RhythmHeavenRemixEditor#222]
### Information
**Log file**: 
![image](https://user-images.githubusercontent.com/34589423/34072935-93637f0e-e255-11e7-94d0-f9744c4de72b.png)

**Editor version**: v3.6.3

### Description
When I tried to use the run_windows.bat file to open, it tells me it wasn't able to access the jar file ( RHRE3.jar). I've updated my Java to the lastest.

### Behaviours
**Expected behaviour**: The editor was supposed to boot.

**Actual behaviour**: When I tried to use the run_windows.bat file to open, it tells me it wasn't able to access the jar file ( RHRE3.jar).

**Comment by chrislo27** [comment]
Did you unzip the zip archive beforehand? 

Windows will tell you this.
![Windows will tell you this.](https://i.imgur.com/zZ1ucKP.png)

**Comment by eridanusofwind** [comment]
I download the files and try to open it with WinRAR. I never see any zipped folders.
![image](https://user-images.githubusercontent.com/34589423/34072911-2a65a87e-e255-11e7-8a77-a1d173081267.png)
This is what I get.

**Comment by chrislo27** [comment]
The download **is** a zip archive. You have to extract it first.

**Comment by eridanusofwind** [comment]
Thanks for the help! I got it to work after I extracted the folder from the zip to my desktop.
