### ISSUE TITLE
Missing Jar File?

### ISSUE THREAD

**Issue by Darthon23** [chrislo27/RhythmHeavenRemixEditor#228]
### Information
**Log file**: 
C:\Users\Downloads\RhythmHeavenRemixEd
itor-dev\distribution>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

You NEED Java 1.8, at least. If the version above is not 1.8+, or if you get an
UnsupportedClassVersionError, update Java.

C:\Users\Downloads\RhythmHeavenRemixEd
itor-dev\distribution>java -jar RHRE.jar
Error: Unable to access jarfile RHRE.jar

C:\Users\Downloads\RhythmHeavenRemixEd
itor-dev\distribution>pause
Press any key to continue . . .

**Editor version**: v.3.6.6

### Description
Everytime I try to boot this program up, it gives me this. I cannot seem to find a way to go around it. I've already tried extracting and redownloading. 

### Behaviours
**Expected Behavior**:
The program would come up.

**Actual behaviour**:
It prompted me that I didn't have the RHRE.jar file within the other files, and closed out of the program.

**Comment by chrislo27** [comment]
Download the zip from here: https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.6.6

Make sure to download the zip file named RHRE3_v3.6.6.zip and NOT the source code.
