### ISSUE TITLE
It wont let me open the file to use it

### ISSUE THREAD

**Issue by GameBoiYT** [chrislo27/RhythmHeavenRemixEditor#229]

**Comment by GameBoiYT** [comment]
Im trying to open it and its telling me to buy something

**Comment by chrislo27** [comment]
Please read the README.

Get a releases from the [releases tab here](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases). Unzip the archive and run (double-click) either the Windows file or macOS/Unix file depending on your operating system.
