### ISSUE TITLE
Change backend from libGDX to JavaFX

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor#232]
### Description
A major backend change needs to happen by September 2018. This is in part due to Java 11 being due at that time and will be the next LTS (Long Term Support) release. Additionally, LWJGL 2 (the current libGDX backend used) already has warnings in Java 9, and no longer works in Java 10 without specific launch parameters.

As a result, I will be rewriting the entire program to use JavaFX instead of libGDX. Due to JavaFX not being included in Java 11, the hope is that the removal of libGDX as a dependency will offset the new ones added for JavaFX. Also, there should be better support regarding text rendering and UI components. While the functionalities of the program will try to remain the same, there are no guarantees and there may be several graphical differences. Another bonus is that there should be more compatibility (related to graphics drivers).

This will likely be one of the longest breaks without updates, even longer than RHRE2 to RHRE3. I am not well-versed in JavaFX currently but will do my best to convert this project.

Even though one could consider this to be a "major change", this will not be versioned as a major update. This update will be developed as a minor version semantically (i.e.: v3.X.0), but as a major change.

**Comment by Jostreator** [comment]
i wish you luck

**Comment by chrislo27** [comment]
The backend change from libGDX to JavaFX is still under consideration, but I would like to mention a (much easier) alternative.

I could bundle JRE8 with the program once Java 11 is out and in widespread use. This would have the download size increase significantly, but by the time September rolls around updates will be much more sparse. It's a decent tradeoff, and much easier for myself.
