### ISSUE TITLE
It doesn't run the apropiated files

### ISSUE THREAD

**Issue by MayaFey11** [chrislo27/RhythmHeavenRemixEditor#234]
### Information
**Log file**: 
[log_2018-04-06_00-46-58.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/1882856/log_2018-04-06_00-46-58.txt)

**Editor version**: (3.9.0)

### Description
I always run the console and the aplication always run normaly, but in the setup always does this extrange run time error. idk if is of the way i put the files in the directory or is something else. Can you please help me?

### Behaviours
**Expected behaviour**: Run the program and download the files properly

**Actual behaviour**: A strange "Run time error"

**Comment by chrislo27** [comment]
Please to `<user>/.rhre3/` and delete the `master/` folder. Relaunch the program.

If you cannot find the `.rhre3/` folder then you may have to enable showing of hidden files and directories.

Please report back if this fix works or not.

**Comment by MayaFey11** [comment]
Yes! It worked. One question: I have to do it every time I want to run the program or is ok now?

**Comment by chrislo27** [comment]
I suspect that there was an abrupt closing of the program during an SFX database update. As long as this doesn't happen I think that you will be fine. However, please do check that this *is* the case and that you don't have to keep deleting the folder (this would be a major issue if this is the case). For now I will close the issue; feel free to re-open it if this problem persists.
