### ISSUE TITLE
I think there might be another language for Love Rap you're missing...

### ISSUE THREAD

**Issue by windows10RHRE** [chrislo27/RhythmHeavenRemixEditor#235]
I think it might be the JA version, but I'm not sure. So, where is it? Is it not possible to obtain yet?

**Comment by chrislo27** [comment]
Please edit your issue with the correct format. This issue will remain invalid until fixed.

**Comment by Miracle22s** [comment]
I think the Japanese and Korean version of Love Rap are missing here, windows10rhre.
