### ISSUE TITLE
Downloading v3.9.1 gives v3.6.4

### ISSUE THREAD

**Issue by eridanusofwind** [chrislo27/RhythmHeavenRemixEditor#236]
Whenever I download 3.9.1, it gives me 3.6.4. It keeps on telling me to update and I've downloaded it multiple times.

**Comment by chrislo27** [comment]
Please run the jar file in the v3.9,1 download after extracting the zip file. If you are merging files use the "Copy and Replace" option.

In the future, please use the issue format provided and provide a meaningful title. "I need help." as a title is undescriptive and generally unhelpful to me at first glance. You may be blocked from posting future issues if this persists. Thank you.
