### ISSUE TITLE
How to install it?!

### ISSUE THREAD

**Issue by Colaseitor** [chrislo27/RhythmHeavenRemixEditor#238]
How can I install the Rhythm Heaven Remix Editor?

**Comment by chrislo27** [comment]
Read the readme first. Go to the [releases page](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases) and download the zip file (not source code).

Please note that in the future the Issues section is not for questions but are for bug reports, and you may be blocked from posting future issues.
