### ISSUE TITLE
Opengl2.0

### ISSUE THREAD

**Issue by Papyrus12** [chrislo27/RhythmHeavenRemixEditor#243]
### Information
**Log file**: [Upload your appropriate log file (found in `\<user>/.rhre3/logs`) here, it contains system information and other important info to help debug the problem]()

**Editor version**: (insert relevant editor version here)

### Description
(describe your problem)

### Behaviours
**Expected behaviour**: <what was *supposed* to happen?>

**Actual behaviour**: <what *really* happened?>

**Comment by chrislo27** [comment]
When making an issue, please ensure to fill out the entire template, or else the issue will be invalid and not looked at.

Also, please avoid making issues and immediately closing them. If this continues, you will be blocked from making further issues on the repository. Thank you.
