### ISSUE TITLE
Problem with Custom JSON File

### ISSUE THREAD

**Issue by kinker31** [chrislo27/RhythmHeavenRemixEditor#244]
### Information
**Log file**:  [log_2018-06-04_21-05-03.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2070570/log_2018-06-04_21-05-03.txt)
**Editor version**: 3.11.0
### Description + Behaviours
Whenever I try loading RHRE3 with a custom JSON file, the program crashes once it gets to said JSON file, leaving behind a "Unexpected character ('{' (code 123)): was expecting comma to separate Array entries" exception error.

**Comment by chrislo27** [comment]
It would help if you actually provided your JSON file.

Your JSON file is invalid. You probably have a misplaced left curly bracket `{`.

**Comment by kinker31** [comment]
That might be the case, but I'll attach the JSON file, just in case.
[data.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2071007/data.zip)

**Comment by chrislo27** [comment]
There is a misplaced left curly bracket. 
![image](https://user-images.githubusercontent.com/6299069/40984419-bb9316de-6896-11e8-89dd-a1739a40f359.png)

You need to write your JSON correctly using a text editor that can do some syntax highlighting, or run it through a JSON verifier. You should know how to use and write JSON before attempting to make custom database entries.
