### ISSUE TITLE
RHRE becoming mute after extended use

### ISSUE THREAD

**Issue by Draster999** [chrislo27/RhythmHeavenRemixEditor#251]
### Information
**Log file**: 
[log_2018-07-21_17-09-08.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2216706/log_2018-07-21_17-09-08.txt)

**Editor version**: v3.12.0

### Description
If I let RHRE run for multiple hours, when I come back, the program becomes completely mute, with no music or sound effects playing.

### Behaviours
**Expected behaviour**: RHRE functions as normally and has sound

**Actual behaviour**: No sound is heard

## Steps to reproduce issue
1. Turn on RHRE
2. Leave Running for multiple hours
3. etc.

**Comment by chrislo27** [comment]
Can you confirm that this happens on v3.12.1?

**Comment by Draster999** [comment]
It does also happens on v3.12.1

**Comment by chrislo27** [comment]
I cannot reproduce the problem after allowing v3.12.1 to idle for around 10 hours.
