### ISSUE TITLE
Quiz Show "correct answer" SFX without cheering

### ISSUE THREAD

**Issue by Castleri** [chrislo27/RhythmHeavenRemixEditor#254]
Greetings, chrislo27 (Sorry if my english is bad)

The Issue that I have with "Rhythm Heaven Remix Editor" is with the SFX of Quiz show
The SFX "Correct Answer" comes with the people´s cheering to the contestant
I would like that you would put another SFX of "Correct Answer" without those people cheering

Thank you

**Comment by chrislo27** [comment]
This has been resolved as of SFX database version [v66](https://github.com/chrislo27/RHRE-database/releases/tag/v66). The "correct sound no applause" cue is available in Quiz Show (Megamix) only.
