### ISSUE TITLE
Micro-Row swim extender & JP Bossa Nova

### ISSUE THREAD

**Issue by Armodillomatt12** [chrislo27/RhythmHeavenRemixEditor#255]
### Information
**Editor version**: v3.13.1

**SFX Database version**: v67

### Description
Micro-Row's Swim pattern isn't a keep the beat pattern. Japanese Bossa Nova also is pending addition.

**Comment by chrislo27** [comment]
This has been resolved as of SFX Database [v69](https://github.com/chrislo27/RHRE-database/releases/tag/v69).
