### ISSUE TITLE
Attempting to drag non-json-indexed custom sfx from the customSounds folder crashes rhre

### ISSUE THREAD

**Issue by minenice55** [chrislo27/RhythmHeavenRemixEditor#260]
### Information
**Log file**: 
[log_2018-09-30_20-34-42.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2432262/log_2018-09-30_20-34-42.txt)

**Editor version**: RHRE version 3.13.3 (also occured on v. 3.13.1)

### Description
While the sfx appears fine in the sfx selector, trying to add them to an existing remix file's timeline will crash the program. The sfx are not setup in a json file. No icon.png has been added to the folder.

### Behaviours
**Expected behaviour**: The editor would allow dragging the sfx into the timeline with no issues.

**Actual behaviour**: Upon clicking a custom sfx from the palette, the program abruptly crashes.

## Steps to reproduce issue
1. Add custom sfx to the customSounds folder, without assigning a custom json or icon
2. Open rhre and an existing remix file
3. Try dragging a custom sfx to the timeline

**Comment by chrislo27** [comment]
Your `more paper mario 2/Ultra Hammer.wav` file is an 8-bit WAV. WAV files that are loaded must have 16 bits per sample.
