### ISSUE TITLE
Export to video

### ISSUE THREAD

**Issue by PandaPJYuri** [chrislo27/RhythmHeavenRemixEditor#264]
## Description of problem

No way to upload to YouTube

## Description of solution

Make an mp4 file when asked which has a black background or what happens when you press play normally. (Preferably the latter)

## Description of alternatives

Screen Recorders, often unreliable.

**Comment by chrislo27** [comment]
This feature request is out of scope for the project.

If you want a fairly reliable screen recorder, [try OBS Studio](https://obsproject.com/download).

If you want a video, use [FFmpeg](https://www.ffmpeg.org/).  
`ffmpeg -i image.png -i remix.ogg output.mp4` where `image.png` is an image, `remix.ogg` is the remix exported as audio, and `output.mp4` being the export file.
