### ISSUE TITLE
I want more tracks

### ISSUE THREAD

**Issue by jackchenxm10** [chrislo27/RhythmHeavenRemixEditor#265]
Having only 5 Tracks strongly limits my creativity. I really need more. Can you help?  

Thanks a lot

**Comment by chrislo27** [comment]
Please, read the documentation before posting an issue.

You can already change the track size with this button on the [toolbar](https://rhre.readthedocs.io/en/latest/Toolbar/).
![image](https://user-images.githubusercontent.com/6299069/46906761-c2f86680-cebd-11e8-9e36-a899d2b360b6.png)

Additionally, use the provided issue templates next time.

**Comment by jackchenxm10** [comment]
Thx, sorry about that.
