### ISSUE TITLE
Annoying Start Properties

### ISSUE THREAD

**Issue by PandaPJYuri** [chrislo27/RhythmHeavenRemixEditor#266]
## Description of problem
Everytime I Want To Add Something To My Long Remix, I Then Need To Listen To The Whole Ting Again And It's Incredibly Annoying
## Description of solution
Either Let Us Place Objects When Paused Or Let There Be An Option In The Top Left Or Bottom Right Hand Corner which lets you change where pressing play starts
## Description of alternatives
N/A
## Additional context
N/A

**Comment by chrislo27** [comment]
Right click to set the playback start marker.

Read the documentation, please.

**Comment by chrislo27** [comment]
Right click to set the playback start marker.  
Read the documentation, please.
