### ISSUE TITLE
Rhythm Heaven Megamix Rest Notation

### ISSUE THREAD

**Issue by Lvl100Feraligatr** [chrislo27/RhythmHeavenRemixEditor#267]
## Description of problem
Rhythm Heaven Megamix uses hex integers (0x30 per beat) to determine beat counts and delays. RHRE uses deciml beats.

## Description of solution
I believe that RHRE could use a hex beat system to make modding easier. A ruler or adjustment to the selection box guides would be useful.

**Comment by chrislo27** [comment]
This feature has been implemented for the next update.  
![img](https://user-images.githubusercontent.com/6299069/47612826-ba686a00-da3f-11e8-91bf-4f0a1632efe8.png)
