### ISSUE TITLE
Add more miscellaneous/supplementary/extra SFX from various minigames

### ISSUE THREAD

**Issue by FruitsPunchParfaits34** [chrislo27/RhythmHeavenRemixEditor#271]
## Description of problem
Not necessarily a major issue in of itself but the addition of adding more miscellaneous SFX that aren't exactly labeled as official cues and are brought about by the player messing around/messing up in general when the actual cues aren't in place/sequence yet such as in:

- Screwbot Factory (the 'clanking' of the claw when either pressing A or B by themselves and the SFX of the claw hitting the conveyor belt) 
- Freeze Frame with the SFX of only the 'camera snapping' when no car cues are present  
- Fan Club with the 'player monkey's clapping' SFX during the end of Fan Club 2 when it is possible to just spam the A button to clap erratically.
- Ringside with the Wrestler's mumbling/coughing when you mess up the cue and essentially just spam the A button
- Karate Man's 'punching' SFX when not pot cues are present
- Figure Fighter's 'blowing up/farting' SFX when messing up the intended cues 
- Love Rap = When the player rapper messes up their cues and their voices are pitched either extremely high/deep
- Fork Lifter = Fork stabbing the ground & the 'coughing' SFX when you mess up
- extra SFX not mentioned, etc

- Another request that also falls somewhat in line is in Exhibition Match with the cue of hitting the ball, would it be possible to obtain/rip the SFX cue of the batter not laughing/exclaiming (which is present during its Remix 8 segments in Fever)  

## Description of solution
The ability/resources to be able to rip these specific SFXs and possibly implement them into RHRE within their intended categories. Also if there are any other SFX or specific cues that others are able to obtain that can be implemented, then that would be extremely beneficial for future remixes.

## Additional Information
- Example of Screwbot Factory's 'claw hitting conveyor belt' SFX = https://youtu.be/obELe9UR5V0?t=32
- Exhibition Match example = https://youtu.be/VkBWoU3_DiY?t=96
- Fan Club 2's 'sole monkey clapping' SFX = https://youtu.be/G_ddZ0sqABg?t=138

**Comment by chrislo27** [comment]
Adding these SFX is not a priority at the moment since custom remixes have perfect runs.

If you are interested in these SFX however you can always add them as custom sounds.
