### ISSUE TITLE
Love Rap - Missing Korean

### ISSUE THREAD

**Issue by NoNoTeal** [chrislo27/RhythmHeavenRemixEditor#272]
## Description of problem
Love Rap (For Fever / Wii) is missing the Korean Language SFX

## Description of solution
Add Love Rap Korean SFX

## Description of alternatives
Rip the audio from a video, remove the music in Audacity or any other sound editor.
Video w/ Korean language found [here](https://www.youtube.com/watch?v=D4ow8DusMpY)

## Additional context
Using version 3.15.3

**Comment by chrislo27** [comment]
>Rip the audio from a video, remove the music in Audacity or any other sound editor.

Please present an example of you doing this. We have not used this technique for SFX for quite a long time due to its inaccuracies in removing the music.

**Comment by NoNoTeal** [comment]
> Please present an example of you doing this. We have not used this technique for SFX for quite a long time due to its inaccuracies in removing the music.

Apparently, Audacity doesn't like Rhythm Heaven voices. It ended up with the audio being scratchy or not even removing the music at all. It ended up failing, basically. There might be another solution with just using ROM files. Major Emulation stuff.

**Comment by chrislo27** [comment]
As of SFX Database [v89](https://github.com/chrislo27/RHRE-database/releases/tag/v89), Korean Love Rap has been added. Many thanks to Lvl100Feraligatr for databasing it, and thanks to NP for romanizing the Korean words.

Please note that you need RHRE [v3.16.0](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/latest) at the very least for this SFX DB update.
