### ISSUE TITLE
Incompatible JNA Native Library

### ISSUE THREAD

**Issue by Rabbidking** [chrislo27/RhythmHeavenRemixEditor#273]
### Information
**Log file**: [log_2019-01-24_12-10-59.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2792851/log_2019-01-24_12-10-59.txt)

**Editor version**: RHRE3_v3.16.0

### Description
I can't open the editor at all. I just keep getting an exception complaining about an incompatible JNA native library installed on my computer. I've spent about an hour looking for any sort of way to figure out how to replace/update/delete it, but I can't find anything, and I have no idea what to do now. I tried to install the latest Java SE development kit, but it didn't fix anything.

### Behaviours
**Expected behaviour**: Program was supposed to open

**Actual behaviour**: throws exception, closes main window one second after opening

## Steps to reproduce issue
1. Run run_windows.bat
2. cmd opens, runs RHRE3.jar
3. throws exception, crashes

**Comment by Rabbidking** [comment]
No, unfortunately that didn't fix anything. I'm still getting the same error as before, even with the latest Nvidia drivers.

**Comment by chrislo27** [comment]
Please try running with a certain system property set:

In Command Prompt/Terminal in the folder where RHRE3.jar is:  
`java -jar -Djna.nosys=true RHRE3.jar`

If this fix works for you, you'll have to keep using it until the next RHRE update. I'll do this flag set in code at launch (but again, only if it works).

**Comment by Rabbidking** [comment]
Alright, doing that worked. I realized I needed to change the nosys variable (like the error told me to do), but I didn't know I could change it in the command line (I don't do a whole lot of command line stuff, if it wasn't immediately apparent lol). Thanks!

**Comment by chrislo27** [comment]
Thanks for the feedback. This has been fixed for the next update.
