### ISSUE TITLE
Setting tempo changes before beat 0 offsets beat 0's time

### ISSUE THREAD

**Issue by GlitchyPSIX** [chrislo27/RhythmHeavenRemixEditor#274]
### Information
**Log file**: <N/A>

**Editor version**: v3.16.0

### Description
Setting a tempo change before Beat 0 will offset the time (weird to explain) in beat 0, delaying the music's start or making the music start faster depending in the change from 120BPM (for instance).
[GIF](https://i.imgur.com/J6rlEHv.gifv)

### Behaviours
**Expected behaviour**: In this case (as seen in the GIF), the marker should still say time 0:00.00 no matter how the tempo is changed before beat 0.

**Actual behaviour**: Time offsets depending on the difference between 120BPM and the beat set before beat 0.

**Additional observation**: [Loading a remix file from a previous version that used a tempo change before beat 0 will show a slight offset.](https://i.imgur.com/rLmeuoi.png)

## Steps to reproduce issue
1. Add a tempo change before Beat 0, where its value is different than 120BPM.
2. Check the time in Beat 0.

**Comment by chrislo27** [comment]
Intentional. See #216.
