### ISSUE TITLE
Monster Goal Crashing the Editor

### ISSUE THREAD

**Issue by EBPB2K** [chrislo27/RhythmHeavenRemixEditor#276]
### Information
**Log file**: [log_2019-03-15_21-11-18.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2973459/log_2019-03-15_21-11-18.txt)

**Editor version:** 3.17.0

### Description
Whenever I try to click on the button for Monster Goal in Playalong, the editor immediately closes. All of the other Playalong options such as Perfect, Life Goal, and Tempo Up work, but Monster Goal is pretty much unusable since the editor crashes whenever I try to use it. Even after uninstalling and reinstalling the editor, the problem still persists.

### Behaviours
**Expected behaviour**: The Monster Goal difficulties work, I can play custom remixes with Monster Goal.

**Actual behaviour**: The editor closes whenever I click on the button to cycle Monster Goal difficulties.

## Steps to reproduce issue
1. Open up a playable remix with playalong input entities.
2. Select "cycle through Monster Goal difficulties".

**Comment by chrislo27** [comment]
Please re-upload a correct log file.

Your date on the log file you sent is dated for Sept. 14, 2018, obviously much earlier than v3.17.0 was released. Attempt to crash the editor again, and upload the *most recently generated* file then.

**Comment by EBPB2K** [comment]
Log file has been fixed.

**Comment by chrislo27** [comment]
Can you confirm that a crash happens when opening the Credits? (Info and Settings -> View credits)

**Comment by EBPB2K** [comment]
Attempted to open the credits, and the editor crashed when doing so.
Log file: [log_2019-03-15_21-27-50.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2973467/log_2019-03-15_21-27-50.txt)

**Comment by chrislo27** [comment]
If you have an installation of Java 8 (not newer) on your computer, please try running RHRE with that. Replace `java` in the batch files with the absolute path of the Java 8 executable in quotes (").

If you do not have an installation of Java 8 on your computer, that's fine -- please mention this and don't do the steps above.

**Comment by chrislo27** [comment]
Thank you for your bug report. A patch version [v3.17.1](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.17.1) has been released that remedies this.
