### ISSUE TITLE
Shrimp Shuffle Pause and Together Cues cannot be moved when split

### ISSUE THREAD

**Issue by oofiederp** [chrislo27/RhythmHeavenRemixEditor#280]
### Information
**Log file**: 
[log_2019-03-21_08-43-24.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/2992286/log_2019-03-21_08-43-24.txt)

**Editor version**: v3.17.1

### Description
When the Together and Pause cues in Shrimp Shuffle are split, attempting to move just the Together and Pause sfx are considered invalid and do not move, even if there are no cues being placed on top of each other. These same things apply to the ABC cues. (Apologies if this is confusing.)

### Behaviours
**Expected behaviour**: Together cues + Pause cues when split should be moved without it being considered invalid.

**Actual behaviour**: 1st 3 cues of "Together" and 1st 4 cues of "Pause" do not move as they are considered "invalid".

## Steps to reproduce issue
1. Place a "Together," "ABC," "Paused" or "Paused ABC" cue on the track.
2. Use the Multipart Splitter tool to split the cues.
3. Attempt to move the 1st 3 parts of the "Together" and "ABC" cue/the 1st 4 parts of their paused counterparts (or move the entire split cue, the 1st couple cues are what can't be moved)

**Comment by chrislo27** [comment]
Fixed in [v103](https://github.com/chrislo27/RHRE-database/releases/tag/v103).
