### ISSUE TITLE
[Launch Attempt] Unable to access jarfile RHRE.jar

### ISSUE THREAD

**Issue by quixQuery** [chrislo27/RhythmHeavenRemixEditor#281]
Downloaded RhthmHeavenRemixEditor-3.17.1.zip
Unzipped the file.
Ran: run_windows.bat (in the unzipped folder under /distribution)

Yields:
>Error: Unable to access jarfile RHRE.jar

It's very possible I downloaded the wrong thing, but after googling was unable to find a resource that specifically tackled this issue. Don't want to be a bother but figured this was the best way of asking what on earth went wrong.

Searching the entire unzipped folder yields no results for "RHRE.jar"

**Comment by chrislo27** [comment]
You have downloaded the wrong file. Do not download the source code if you are looking to just run the program.

Download the latest zip file (at the time of this writing, it is **RHRE_v3.17.1**.zip) [from here](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/latest).
