### ISSUE TITLE
Better Control Scheme for Toss Boys

### ISSUE THREAD

**Issue by GinoTitan** [chrislo27/RhythmHeavenRemixEditor#283]
## Description of problem
Playing Toss Boys with J and K is unnecessarily difficult, as the game relies on the position of the GBA's buttons.

## Description of solution
Adding the N key as alternative B input would fix this problem.

## Description of alternatives
Adding the option to remap inputs on the keyboard would be a more general solution.

Thanks!

**Comment by chrislo27** [comment]
Thank you for your concern. I have added two new control schemes for the next update, `QWERTY WASD/JN` and `AZERTY ZSQD/JN`.  
![image](https://user-images.githubusercontent.com/6299069/55688536-79e61400-592e-11e9-8a29-724ef2bec867.png)

In the meantime, you can actually manually set a keybinding, but it takes a bit of work.  
Make sure the program is closed, and go into `<user home>/.prefs/RHRE3` and open it with Notepad++. Look for the entry titled `playalongControls`.

![image](https://user-images.githubusercontent.com/6299069/55688520-4f945680-592e-11e9-84a2-8b3f2778d06d.png)

You can set each of the button codes using the numbers found in [this file](https://github.com/libgdx/libgdx/blob/642f68eb261fca704afd445386763f86045dda93/gdx/src/com/badlogic/gdx/Input.java#L134). In your case, the `N` key is `42`. Here's an example:  
![image](https://user-images.githubusercontent.com/6299069/55688523-5d49dc00-592e-11e9-9870-951a55238237.png)

Save, and open RHRE. It should show up as a "Custom" keybinding.

**Comment by GinoTitan** [comment]
Thank you!
