### ISSUE TITLE
RHRE Can't access internet(Or something)

### ISSUE THREAD

**Issue by TheGLander** [chrislo27/RhythmHeavenRemixEditor#285]
### Information
[log_2019-04-15_20-20-12.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/3081368/log_2019-04-15_20-20-12.txt)
(Sorry, i included the portable version log, but i doesn't matter, it doesn't work on main version too)

**Editor version**: 3.18.0

### Description
It can't get past the version check, I think it just can't access internet.

### Behaviours
**Expected behaviour**: Go past Checking for a new version(I think)

**Actual behaviour**: Stuck at it with no internet usage

## Steps to reproduce issue
1. Just...Use my setup, I don't know

**Comment by chrislo27** [comment]
Your steps to reproduce the issue are insufficient.  
I have checked your log file and the error it reports should not happen; I checked the distribution copy of the update.

Please delete your existing RHRE download, and [redownload](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/download/v3.18.0/RHRE_v3.18.0.zip) the program.

**Comment by TheGLander** [comment]
Weird, I redownloaded RHRE multiple times, the outcome is the same...

**Comment by chrislo27** [comment]
I recompiled the program and [reuploaded it here](https://github.com/chrislo27/RHRE-snapshots/releases/tag/v3.18.0-TEST). Please download this, and be sure to delete any previously downloaded RHRE versions.

Again, the error in your log file should not happen; I decompiled the class file where that error points and there is the `setName(String)` method there as expected.

**Comment by TheGLander** [comment]
Huge thanks, It downloaded everything and opened the editor.
