### ISSUE TITLE
A Bug Issue

### ISSUE THREAD

**Issue by goldynflower** [chrislo27/RhythmHeavenRemixEditor#287]
So it's this problem with the track height, I can't increase it :( Can you fix?

**Comment by chrislo27** [comment]
Please use the issue format next time. Also, [read the documentation](https://rhre.readthedocs.io/en/latest/) before making GitHub issues.

Change the track height using the appropriate button on the toolbar. https://rhre.readthedocs.io/en/latest/Toolbar/#change-track-size
