### ISSUE TITLE
It wont lt me get past the "Click any key to continue" screen?

### ISSUE THREAD

**Issue by DatCatDatIsAGirl** [chrislo27/RhythmHeavenRemixEditor#288]
I've extracted the files, tried every option, but if I press a key, it just closes. nothing else happens. Send help?

**Comment by PointyMorper** [comment]
I have the exact same problem. someone help us!

**Comment by chrislo27** [comment]
Respect the [issue format template](https://github.com/chrislo27/RhythmHeavenRemixEditor/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md).

You are not going to get help until you correct it, **and** provide much more detail as to what is going on. Right now, I have **zero** context on what is happening. Even if I wanted to, I could not help you.

For one, you could start by screenshotting the terminal output before "press any key to continue". I suspect you didn't [follow the installation instructions](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation) which says to download from [the releases page](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/latest), NOT the source code.

Please, be considerate next time. Templates and guidelines exist for a reason -- to make everyone's lives easier on your part and my part especially. Asking questions like this is frankly a waste of my time to try to decipher and answer.
