### ISSUE TITLE
Double/halve tempo function does not respect limits

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor#291]
### Information
**Editor version**: v3.18.1

### Description
The quick double/halve function of the Tempo Change tool, added in pull request #290, does not respect the artificial limitations of [1, 600] BPM. As such, one can eventually approach 0.0 BPM by repeatedly halving the BPM (lim_n->inf approaches 0) and one can get extremely high BPM values the editor isn't supposed to handle by doubling repeatedly.

### Behaviours
**Expected behaviour**: Strict cutoff when placing a tempo change from [1, 600] (defined by `TempoChange.MIN_TEMPO` and `TempoChange.MAX_TEMPO`)

**Actual behaviour**: The limits are ignored

## Steps to reproduce issue
1. Place a tempo change down at beat zero.
2. Place another tempo change down at beat one, holding SHIFT or ALT. 
3. Repeatedly place tempo changes ahead of the last one, still holding SHIFT or ALT. The tempo will eventually go past 600 or below 1.

**Comment by chrislo27** [comment]
This has been fixed on the dev branch as of https://github.com/chrislo27/RhythmHeavenRemixEditor/commit/003ebf0e8494ade483ef0908c9a57089e9bda513 and will be published with the next release.

**Comment by Kamayana** [comment]
Apologies for this, I probably should've enforced limits on it myself. I was so impressed that the program still functioned as expected even at 1000000+ BPM that I let it stand.

**Comment by chrislo27** [comment]
No worries. I should've caught this while reviewing, anyway.
