### ISSUE TITLE
Screen resolution adaption

### ISSUE THREAD

**Issue by JG-GIT** [chrislo27/RhythmHeavenRemixEditor#294]
Currently, RHRE has been using nearest-neighbour stretching, which makes things sometimes look chunky on integer stretching. This annoys me a bit, as some 21:9 monitors, if in windowed fullscreen, make everything look janky.

For this, I would like a "Disable stretching" option, that will make it adjust the screen without stretching. [example: 2520x1080 would extend the background borders, use non-integer upscaling methods for game icons, evenly distribute UI width, and space out top UI elements] This would remove some frustrations from 21:9 monitor users.

I haven't been able to find any alternatives for this, yet. And if you ignore this, it's completely fine.

![rhre](https://user-images.githubusercontent.com/39865752/57343069-0850df80-70ff-11e9-9db5-a8ad16d8864c.PNG)

**Comment by chrislo27** [comment]
Use the provided issue templates next time.

The program is *designed* on the assumption that the displayed area has an aspect ratio of 16:9, one of the most common aspect ratios. All UI elements are positioned as such. Accordingly, the program will attempt to render at the closest available 16:9 resolution, which will result in stretching or distortions at different aspect ratios.

I have no plans of natively supporting non-16:9 aspect ratios. Please use either a 16:9 window setting or attempt to implement it yourself by forking this project and submitting a pull request. Additionally, you may want to try to see if your monitor supports using a 16:9 resolution (with letterboxing on the sides).
