### ISSUE TITLE
Rendering bug with glass entities and minimap preview

### ISSUE THREAD

**Issue by bin5s5** [chrislo27/RhythmHeavenRemixEditor#297]
## Log File:
[log_2019-05-28_08-18-53.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/3228433/log_2019-05-28_08-18-53.txt)

## Editor Version
 3.18.2
## Description

When I hover over the mini-map in the bottom right side of the screen a black box appears and the game shows up in the background.

## Behavior
It's supposed to show the mini-game in a box while your current screen stay's the same.

It actually showed the mini-games on the backgrounds while the box where the mini-games used to be is now black.

## Steps to reproduce issue
Just hover the mouse over the mini-map (Or turn it on in the settings if you turned it off) and that's how I got the black screen

## Picture Proof
![Zoom](https://user-images.githubusercontent.com/42101010/58491721-237aa200-8135-11e9-8c87-660390caada4.png)

**Comment by chrislo27** [comment]
Unfortunately I'm not currently able to reproduce this bug. Could you please change the theme to "Classic Dark" and take another screenshot? What I'd like to see is if the black rectangle is the same colour as the track line, which may help me trace this problem.

**Comment by bin5s5** [comment]
Look's like the option themes are only affected for some reason, I also used Tengoku's option theme for the background and it had the same effect.
![Zoom CD](https://user-images.githubusercontent.com/42101010/58503709-c2f85e80-814e-11e9-82ee-ef11ece4032f.png)

**Comment by chrislo27** [comment]
Thank you! I can now reproduce the bug. I'll work on it and get back to you in the next day or so.

**Comment by chrislo27** [comment]
This has been fixed as of commit 69c8ecd295322110e2bb9e13b157e502a677308a. I will label this issue as fixed (please don't close this issue, I will do it when the next release happens). 

Thank you for your help!
