### ISSUE TITLE
Fan Club (Megamix) "ohh" should not change pitch with tempo

### ISSUE THREAD

**Issue by DeckOfNoobs** [chrislo27/RhythmHeavenRemixEditor#298]
### Information
**Editor version**: v3.18.2

**SFX Database version**: v110

### Description
Fan Club (Megamix)'s "ohh" cue changes its pitch based on the current tempo. This, as a result, makes the pattern inaccurate to the actual game, which consistently keeps the same pitch.

**Comment by chrislo27** [comment]
Fixed as of SFXDB v112.
