### ISSUE TITLE
is there any way to skip sfx database update?

### ISSUE THREAD

**Issue by MarioWahoo** [chrislo27/RhythmHeavenRemixEditor#299]
### Information
**Editor version**: 3.18.6

**SFX Database version**: current

### Description
is there any way to skip sfx database update?

even if theres no way
is it possible to load the sounds from database without saving them?
i have little disk space because whenever i cleaned up like 600 MB after some minutes.. boom 0B avaiable. Also it takes too long and even if i have sufficient amount of disk space it will just say an runtime error occured. 

(in java console it says Caused by: java.io.IOException: Za ma│o miejsca na dysku (from polish: Insufficient Amount of Disk Space))

**Comment by chrislo27** [comment]
While there is a way to skip the SFX database update check [using the `--skip-git` launch argument](https://rhre.readthedocs.io/en/latest/Launch-arguments/), there is no way to not have the SFX database on disk. It's composed of thousands of files that take advantage of being stored on disk.

However, the SFX database when unpacked (for me) is 191 MB occupying 202 MB of space. It certainly would not be as large as 600 MB, so perhaps there are other files or programs on your computer that use a lot of disk space.
