### ISSUE TITLE
Issue with opening program 

### ISSUE THREAD

**Issue by ihopethisworks1** [chrislo27/RhythmHeavenRemixEditor#302]
Whenever I hit the correct window launcher it just takes me to the command prompt and says “Java is not recognized as an internal or external command, operable program or batch file.

After that, it asks me to press any key to continue and then the application closes

**Comment by chrislo27** [comment]
Did you [install Java according to the installation prerequisites?]

**Comment by ihopethisworks1** [comment]
> Did you [install Java according to the installation prerequisites?](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements)
