### ISSUE TITLE
Music previsualization don't works

### ISSUE THREAD

**Issue by Yacineuh** [chrislo27/RhythmHeavenRemixEditor#303]
### Information
**Log file**: [log_2019-09-07_20-03-05.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/3586895/log_2019-09-07_20-03-05.txt)

**Editor version**: 3.18.7

### Description
When i put a music for the remix, it says the music is here but, it does not play, even for the tempo. My theory is when i import the music, the game thinks that is successfully imported, but he thinks that the length is zero, or anything like that, because i don't see waveform even when its activated.
Maybe if you try to add a default tempo value that will be set when creating a new remix it would correct the problem.

### Behaviours
The music should be playing

**Actual behaviour**: Nothing happens when i try to press gray things

## Steps to reproduce issue
1. I don't know, because it can be only on my computer
2. I tried all audio files types, i even tried to launch the JAR directly, and the BATs files

![image](https://user-images.githubusercontent.com/55030860/64478551-295b3700-d1aa-11e9-93dc-f2ecd056ea36.png)

![image](https://user-images.githubusercontent.com/55030860/64478554-3710bc80-d1aa-11e9-8a1a-8a9830409dff.png)

**Comment by Yacineuh** [comment]
Issue closed because normaly, the tapalong is for calculating the bpm, and is not automaticly applied
we must press this button and put the number in the start of the song. 
![image](https://user-images.githubusercontent.com/55030860/64478832-996bbc00-d1ae-11e9-8658-3f004aae1d9e.png)

**Comment by chrislo27** [comment]
This is intentional behaviour [as of v3.18.0](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.18.0) and will not be addressed.
