### ISSUE TITLE
App will not open on MacBook Air

### ISSUE THREAD

**Issue by jonythegamer** [chrislo27/RhythmHeavenRemixEditor#304]
### Information
**Log file**: [Upload your appropriate log file (found in `\<user>/.rhre3/logs`) here, it contains system information and other important info to help debug the problem]()

**Editor version**: (insert relevant editor version here)

### Description
(describe your problem)

### Behaviours
**Expected behaviour**: <what was *supposed* to happen?>

**Actual behaviour**: <what *really* happened?>

## Steps to reproduce issue
1. Step one
2. Step two
3. etc.

**Comment by chrislo27** [comment]
Please fill out the issue template, otherwise this issue will be closed.
