### ISSUE TITLE
Mac sh

### ISSUE THREAD

**Issue by Fearraticc** [chrislo27/RhythmHeavenRemixEditor#307]
so how can I run a sh file run to use Rhythm heaven remix editor??

**Comment by chrislo27** [comment]
After downloading and unpacking the [latest release](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/latest), there is a file named `run_macOS-linux.sh` inside the "Rhythm Heaven Remix Editor" folder. You can run that file using the command line or by double-clicking the file. If it is not executable, you can `chmod` that file.

**Comment by Fearraticc** [comment]
how?

**Comment by Fearraticc** [comment]
I'm a noob at this stuff
