### ISSUE TITLE
macOS Crash on Startup

### ISSUE THREAD

**Issue by NoNoTeal** [chrislo27/RhythmHeavenRemixEditor#308]
### Information
**Log file**: [log_2020-03-02_18-42-21.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4279291/log_2020-03-02_18-42-21.txt)

**Editor version**: v3.19.2

### Description
When opening the RHRE .jar file with `java -jar -Xmx1024m RHRE.jar` in Terminal (same command found in the .sh file), the jar file opens, changes window size with the same image, but cropped on screen and then crashes. 

### Behavior
**Expected behavior**: I would be able to get into the application and start making custom remixes

**Actual behavior**: Application got past the loading screen, window size changed, the loading screen was cropped because of the window getting smaller, then stayed for about a second like that, and crashed.

## Steps to reproduce issue
1. Download [3.19.2](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.19.2)
2. Open RHRE folder with Terminal
3. Run command `java -jar RHRE.jar` OR `java -jar -Xmx1024m RHRE.jar`

**Comment by chrislo27** [comment]
Hi, thanks for your bug report.

I notice that your log file reports your macOS version to be 10.13 (High Sierra), and the latest macOS version is 10.15 (Catalina). While currently the recommended specs on the front page say that 10.11 (El Capitan) is the minimum macOS version, it's possible that that has to be updated. 

If you so desire, you can update your macOS version through the App Store and see if RHRE works. If you do this, please reply with a comment on this issue what version you updated to and if that worked or not.

Thank you for your patience!

**Comment by NoNoTeal** [comment]
I most likely will not be upgrading to macOS 10.15 soon as I'm a little concerned about performance issues by making my mac slower and downgrading back to High Sierra can be a very tedious task to do.

**Comment by chrislo27** [comment]
I understand your concern with updating to Catalina. Would you consider updating just one version up (instead of two) to [Mojave](https://support.apple.com/en-us/HT210190)?

**Comment by NoNoTeal** [comment]
I could do Mojave but the mac I'm using started out with either Yosemite or El Capitan, but I'm also concerned with performance issues with that, I looked at a Reddit [post](https://www.reddit.com/r/apple/comments/adpp7k/whats_your_mojave_experience_for_the_macbook_pro/) and everything seems to be ok for them, so I'm considering on that. I might try experiment with a VM first to see how that works.

**Comment by chrislo27** [comment]
Hi, would you mind updating us on the situation? This issue may be closed due to inactivity in a few days.

Right now I've updated the README on the main page to promote the minimum macOS version as Mojave since I can confirm it works on that version.

**Comment by NoNoTeal** [comment]
i tested it with a vm on mojave, and I forgot which java version but it crashed on one of them... Either Java 1.8 or 9, or maybe even 13 with v3.19.2

**Comment by chrislo27** [comment]
I would appreciate it if I could get a terminal screenshot(s) that clearly show the Java version (obtained from `java -version`) and any error stacktraces. Thank you.

**Comment by NoNoTeal** [comment]
i deleted the vm due to storage issues, i might do this again when i can, but I'm not sure if using a vm is the best for this type of situation

**Comment by chrislo27** [comment]
Closed due to inactivity. Please reopen the issue if there are updates.
