### ISSUE TITLE
MacOS Mojave Crash on Startup

### ISSUE THREAD

**Issue by bruhmomento567** [chrislo27/RhythmHeavenRemixEditor#309]
### Information
**Log file**: N/A, never able to open up program

**Editor version**: Every version from 3.19 onwards, I have tried this with

### Description
I am running on macOS Mojave 10.14.6 and every time I run RHRE.jar it boots up until the very last part of the progress bar, and then crashes

### Behaviours
**Expected behaviour**: Remix editor should boot up successfully and I can use the program as normal

**Actual behaviour**: Program boots up and crashes before done loading

## Steps to reproduce issue
1. Run on macOS Mojave 10.14.6
2. Start up Remix Editor
3. Software will crash before loading is completed

**Comment by chrislo27** [comment]
Please provide the log file generated for this session (even though it crashed, it does generate). The log file contains important information to aid in resolving this issue. You can find the log file for your session in `~/.rhre3/logs/`; they are timestamped.

**Comment by bruhmomento567** [comment]
Yeah, will do! I just wasn't sure if I could considering it never ran successfully, but I will find it for you.

**Comment by bruhmomento567** [comment]
I've searched around for a few minutes, and I can't find the log file. Out of which one of these folders in the console has the logs
<img width="146" alt="Screen Shot 2020-03-20 at 2 28 35 PM" src="https://user-images.githubusercontent.com/61330111/77194920-2fb26000-6ab7-11ea-9779-a34b375d7e7c.png">

**Comment by chrislo27** [comment]
In Finder, go to your user home, and look for the `.rhre3` folder. If it isn't visible, press Command+Shift+Dot to toggle viewing of hidden files/folders. Then enter the `.rhre3` folder and enter the `logs` folder inside of that. Each log file is timestamped -- if you have doubt, run RHRE again, wait for it to crash, and take the most recently created file and upload it here as a comment.

**Comment by chrislo27** [comment]
Closed due to inactivity.
