### ISSUE TITLE
Pitch-shifting gleeClub/screamBegin and gleeClub/screamLoop results in dissonant chords

### ISSUE THREAD

**Issue by ahemtoday** [chrislo27/RhythmHeavenRemixEditor#31]
we need some way to pitch-shift each member individually to be able to make proper chords, but i don't know where we'd acquire the SFX for this

**Comment by chrislo27** [comment]
This issue has been "resolved" through the following:
* Make `gleeClubX/screamLoop` unpitchable

**Comment by chrislo27** [comment]
This issue will be **indefinitely** closed because of the following reason(s):
* The version of RHRE this pertains to is out of date
