### ISSUE TITLE
I Keep Getting Stuck On The SFX Database Update Screen

### ISSUE THREAD

**Issue by Jet002** [chrislo27/RhythmHeavenRemixEditor#310]
So one day I wanted to make a remix with your remix maker, but every time I try to open it, It will say that theres a timeout error after about 2 -10 seconds. I'm sorry if this sounds like a demand, but can you please try to fix this?

**Comment by chrislo27** [comment]
Hi, I'm sorry to hear you're having problems with SFX Database updating. Please send a log file, found at `<user home>/.rhre3/logs/` (you may have to enable viewing of hidden files/folders), or at least a screenshot of the crash screen or error.

**Comment by Jet002** [comment]
![2020-03-21 (1)](https://user-images.githubusercontent.com/62452416/77236180-948eb880-6b92-11ea-94ec-f870480b409a.png)
So, everytime i try to open up RHRE 3.19.2(hope thats right) it waits 2 -10 seconds, and keeps showing me this, I checked my wifi 3 times, and its very fast, but this screen still shows up.

**Comment by chrislo27** [comment]
Please send the associated log file, or the console output in a text file.

**Comment by chrislo27** [comment]
Closed due to inactivity. Reopen this issue again if you have more information and the log file.
