### ISSUE TITLE
macOS 10.15 (Catalina) requires code signing, SoundStretch executable is flagged by the system

### ISSUE THREAD

**Issue by FruitsPunchParfaits34** [chrislo27/RhythmHeavenRemixEditor#311]
### Information
**Log file**: [log_2020-03-22_09-12-48.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4364397/log_2020-03-22_09-12-48.txt)

**Editor version**: v3.19.2

### Description
I just recently updated to the recent Mac OS Catalina (Ver. 10.15.3) and then downloaded the most recent RHRE3 update file (v3.19.2) and it works fine. However when trying to open any of my previous custom remix files that I've completely previously saved in a prior version, it immediately crashes and pops up with a notification screen of all the files and basically what went wrong. 

(NOTE: When the program also tries to load the entities along with the remix a pop up appears halfway through that says '“SoundStretch_macOS” will damage your computer. You should move it to the Bin.')

### Behaviours
**Expected behaviour**: Load my previous custom remix file and be able to access the remix.

**Actual behaviour**: The program crashes when trying to open previous files.

## Steps to reproduce issue
1. Open RHRE3
2. Go to Open Remix tab
3. Select and open previous custom remix file and load it

![Screen Shot 2020-03-22 at 9 21 20 am](https://user-images.githubusercontent.com/41479118/77238408-b4ba8800-6c23-11ea-85d2-9b763b2e4e26.png)

**Comment by chrislo27** [comment]
Hi, sorry to hear you have this problem. It seems that macOS 10.15 (Catalina) has upped security requirements for programs. Specifically, "SoundStretch_macOS" is a sub-program I use to handle the time stretching function in RHRE, you can [find its website and source code here](https://www.surina.net/soundtouch/download.html). I will look into building that program myself and certifying it but that may take upwards of several weeks.

**For the time being, a temporary solution** is to disable time stretching in Info and Settings. You can do that by loading the program, clicking the Info and Settings button on the toolbar in the upper-rightmost corner, and selecting the Disable time stretching option.

Thanks for your patience.

**Comment by FruitsPunchParfaits34** [comment]
That's okay. Thanks for your efforts in fixing these issues. I'm just glad that I can access my old files now and tweak them after not using the program for a couple months due to me not updating my Mac for a while. Thanks again and take your time with with fixing the issues.

**Comment by chrislo27** [comment]
Status update! I figure I should say something since this issue is sort of in progress.

I added SoundStretch time stretching support for Linux, though that isn't exactly related to this issue. What I think I may do is abstract that further and add a [FFmpeg](https://ffmpeg.org/) backend, since it supports time stretching through the `atempo` filter. Then it should be relatively trivial to support switching time stretching backends for non-macOS platforms (Windows/Linux can choose between SoundStretch or FFmpeg, macOS can only use FFmpeg). However, I don't currently have access to a Mac platform or VM for testing, and I hope to work on that soon when I have time.

**Comment by chrislo27** [comment]
Closed because macOS support in RHRE was dropped as of August 14, 2020.
