### ISSUE TITLE
Can't change properties like BPM and Song Volume

### ISSUE THREAD

**Issue by PichuBoy000** [chrislo27/RhythmHeavenRemixEditor#312]
I have decided to update RHRE to version 3.19.3 and suddenly i can't change things Like BPM, Song Volume, and Sound Pitch, I have tried everything and nothing worked.

**What Was Expected**: To change settings for things

**What happened**: Cant change anything

I might be able to do something so i can change properties, but i have not yet known about what i should use.

**Comment by chrislo27** [comment]
Hi, sorry to hear you're having problems.

Please follow the provided [bug report issue template](https://raw.githubusercontent.com/chrislo27/RhythmHeavenRemixEditor/dev/.github/ISSUE_TEMPLATE/bug_report.md) so I can better help you. Please upload a log file, you can find them at `<user home>/.rhre3/logs` (you may have to enable viewing of hidden files and folders), marked with the time of program launch.

Also, please try restarting your computer; this should be the first thing you try. It seems so far it is related to the scroll wheel on your mouse; have you tried using the UP and DOWN arrow keys in-place of scrolling? Please also try using another mouse peripheral.

**Comment by chrislo27** [comment]
Thank you for reporting this. After further investigation a bug was found related to the playback speed control. Please redownload v3.19.3.

This issue will now be closed because it has been resolved with a reupload of v3.19.3.
