### ISSUE TITLE
Crash on loading SFX when there is an RSDE custom sound with language: null

### ISSUE THREAD

**Issue by Kamayana** [chrislo27/RhythmHeavenRemixEditor#316]
### Information
**Log file**: [log_2020-04-21_23-54-33.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4513863/log_2020-04-21_23-54-33.txt)

**Editor version**: v3.19.4

### Description
I'm trying to use RSDE to adjust the Love Lizards sound effect, but when I do this RHRE hard crashes during SFX loading. 

Going by the error of `java.lang.IllegalStateException: Key not found in mappings: sfxdb_langicon_???_pixmap`, I looked into the data.json of the custom sound and found that the culprit was `  "language" : "null",`. After removing that line entirely the custom sound loads as expected and everything works fine, but if I later edit the sound with RSDE it'll re-add `  "language" : "null",` and crash RHRE again. If I set a language within RSDE, to Japanese or something, it'll also load properly. It seems like it's specifically the null value that's breaking it because there RHRE can't find sfxdb_langicon_???_pixmap.

I wasn't sure under which repository to report this issue, since the problem is either RSDE's for adding `  "language" : "null",`, or RHRE's for not being able to handle it.

### Behaviours
**Expected behaviour**: Loads normally, with my custom Love Lizards wholly replacing the stock Love Lizards.

**Actual behaviour**: Crashes during SFX loading.

## Steps to reproduce issue
1. Open RSDE (latest version, v1.1.4).
2. Click "Copy and Edit Existing Game Definition".
3. Select a game with no language like Love Lizards. Leave game ID as is. Click Continue.
4. Close RSDE.
5. Open RHRE. It'll crash during SFX loading.

**Comment by chrislo27** [comment]
Hi, thanks for your bug report. It is indeed a problem with RSDE, which has been neglected over time... It has to do with the JSON serializer not behaving the way I expect it to. I will work on that and release RSDE v1.1.5 shortly.

**Comment by chrislo27** [comment]
It should be fixed now as of [RSDE v1.1.5](https://github.com/chrislo27/RSDE/releases/tag/v1.1.5). Thank you for your patience!
