### ISSUE TITLE
A remix from an older version of RHRE3 (3.14.0 SFX v78) crashes instantly upon either trying to enter the editor or playing the remix.

### ISSUE THREAD

**Issue by oofiederp** [chrislo27/RhythmHeavenRemixEditor#318]
### Information
**Log file**: 
[log_2020-05-17_13-25-47.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4640785/log_2020-05-17_13-25-47.txt)
[log_2020-05-17_13-39-25.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4640786/log_2020-05-17_13-39-25.txt)
[log_2020-05-17_13-51-29.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4640809/log_2020-05-17_13-51-29.txt)

RHRE3 file for any additional reference 
[RHRE3 File.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4640805/RHRE3.File.zip)
I had to put it in a .zip file as GitHub does not support .rhre3 files.

**Editor version**: RHRE3 v3.20

### Description
In attempting to play a remix in RHRE3 v3.20, one file in particular crashes either when I load it or try to play the remix. Another file in the 1st log file loads and works fine, but this one for some reason just crashes, which didn't happen in the past. It is worth mentioning that the remix file is from an older version as I was trying to remake it, from v3.14.0 and SFX Database v78.

### Behaviours
**Expected behaviour**: The file would load, same as the other ones, and would then be able to be edited and listened to via the play button.

**Actual behaviour**: Either the remix crashed RHRE instantly, or I got to the editor, but it just crashed.

## Steps to reproduce issue
1. Open RHRE3 v3.20 via the "run_windows" command.
2. Load the remix file above.
3. Either it will crash instantly upon loading, or you will be able to get to the editor, only for it to crash upon trying to play back the remix.

**Comment by chrislo27** [comment]
Issue resolved outside of GH issues by installing 64-bit Java.
