### ISSUE TITLE
something crashed

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor#319]
### Information
**Log file**: 
[log_2020-05-17_21-25-11.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4641731/log_2020-05-17_21-25-11.txt)

**Editor version**: 3.19 or later

### Description
The editor keeps crashing whenever I use a version past the 3.18s. It reaches the part where it loads the games, but after that, the editor crashes.

### Behaviours
**Expected behaviour**: The editor continues existing

**Actual behaviour**: The editor crashed

## Steps to reproduce issue
1. Use an RHRE version older than 3.19
2. Do whatever caused this to happen
3. Update the editor
4. Open it

also haha 319 get it because it happens on 3.19 or later haha funny

**Comment by chrislo27** [comment]
Please remove all custom sounds, if any, and try again. You can find them at `<user home>/.rhre3/customSounds`.

Please also be more detailed with your report information. "Do whatever caused this to happen" does not offer me any help on how to resolve your issue.

**Comment by GuardedLolz** [comment]
It worked. My apologies.
