### ISSUE TITLE
Martain: ???? ??

### ISSUE THREAD

**Issue by TheEmeraldCreeperRB** [chrislo27/RhythmHeavenRemixEditor#320]
### Information
**Log file**: [Upload your appropriate log file (found in `\<user>/.rhre3/logs`) here, it contains system information and other important info to help debug the problem]()

**Editor version**: (3.20.0)

### Description
(The Program crashed when i tried Opening a Remix i had made. I Dont know what caused it, and i have tried Uninstalling the Previous versions of the editors i have, but it didnt seem to fix the problem.)

### Behaviours
**Expected behaviour**: <My Remix was supposed to load Normally>

**Actual behaviour**: <The Program Crashed.>

## Steps to reproduce issue
1. Step one Load Remix
2. Step two Program Crash

Other:
The program doesn't crash when i Load remixes that only use One Game for Some reason, so that might help.

**Comment by chrislo27** [comment]
Please upload your appropriate log file (found in the `<user home>/.rhre3/logs` directory), it contains system information and other important info to help me debug the problem.

**Comment by chrislo27** [comment]
Closed due to insufficient info and inactivity.
