### ISSUE TITLE
Can't Open the Program I'm using windows 10

### ISSUE THREAD

**Issue by GeorgBorg** [chrislo27/RhythmHeavenRemixEditor#321]
### Information
**Log file**: I couldn't find my log file, I'm sorry, I tried as hard as I can

**Editor version**: (insert relevant editor version here)

### Description
When I tried to open it,  just said: `Error: Unable to access jarfile bin/RHRE.jar`
### Behaviours
**Expected behaviour**: The program was supposed to load up

**Actual behaviour**: I got an error message

## Steps to reproduce issue
1. I don't know

**Comment by chrislo27** [comment]
Hi, please make sure to [follow the installation instructions](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation).

When you download the `RHRE_v3.20.0.zip` file, make sure you extract it. On Windows 10, you will see this button in the File Explorer: 
![image](https://user-images.githubusercontent.com/6299069/83301151-f9c3e300-a1ad-11ea-9aa6-9ee8fd3c5611.png)

Then, double click the `run_windows.bat` file. It looks like this: 
![image](https://user-images.githubusercontent.com/6299069/83301187-0811ff00-a1ae-11ea-9ecd-e7764a54040f.png)

**Comment by GeorgBorg** [comment]
ok thanks

**Comment by GeorgBorg** [comment]
I extracted it and it still keeps on giving me the same error.

**Comment by chrislo27** [comment]
Please follow the [installation instructions](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation) and you will be good to go.
