### ISSUE TITLE
Auto-update timeout is too short (60 sec)

### ISSUE THREAD

**Issue by Maziodyne** [chrislo27/RhythmHeavenRemixEditor#322]
## Description of problem
Auto-Update timing out before completing.

## Description of solution
It seems like the Auto-Update involves a 1-minute time cap, and timeout errors if it doesn't finish before then. Unable to inspect code myself, so I'm forced to only wonder if its actually been coded this way, and request that this either be removed or extended if it is.

## Additional context
When trying to auto-update from v3.20.0 to v3.20.1, it ran into a timeout error. Initially, I thought this might have been because I'd tabbed to the Discord app while it was updating, so I closed that and Chrome, and tried again, only for it to still timeout at about 80% completion. I took a closer look at the on-screen error information the second time, then inspected it again on the third timeout, compared the two, and noticed both were exactly 60000ms (60 seconds).

**Comment by chrislo27** [comment]
Hi, I would greatly appreciate it if you could upload a log file (or multiple) for the sessions when you had the timeout error.

**Comment by Maziodyne** [comment]
Ah shoot, I should've thought about that. Can't seem to find anything logging what happened yesterday anymore, spent a good couple hours or so looking through files. Mostly found a lot of blanked or purged log files that would no longer open. Sorry about that. I can at least give you a screenshot of what the updater itself says on-screen for the error, but not much else for the moment, as I've already updated to v3.20.1 manually. [Here's the error message.](https://i.gyazo.com/a4d0c44cf95bc39833ebf765c6b07858.png) As far as I can tell and remember, it was identical to this every time I got it.

**Comment by chrislo27** [comment]
Thanks for your report! You were right, apparently the default request time is only 60 seconds. That might be sufficient for small requests but not for big downloads.

As of commit 132154a3688cfdf985c6e8b8973c9c45e11cb8b0 I have extended the total request time to a very large value (2 billion ms), and the read timeout (time between reads, used to check when the download stalls) to 120 seconds.

The fix will be deployed in the next version (v3.20.2 or v3.21.0) and I will close the issue when that is published.

**Comment by Maziodyne** [comment]
Great, thanks! Glad to be of assistance.
