### ISSUE TITLE
RHRE crashes when loading a remix.

### ISSUE THREAD

**Issue by RushKoopa** [chrislo27/RhythmHeavenRemixEditor#324]
### Information
**Log file**: [log_2020-06-12_09-01-57.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4770933/log_2020-06-12_09-01-57.txt)

**Editor version**: 3.20.1

### Description
I was working on a remix of a fairly long song (about 30 minutes long or so) and took a break, when I came back to work on it later, RHRE would crash instead of loading it.
I've tried adding memory to RHRE in the .bat file, that just makes it crash quicker.
I've also tried downloading the 64 bit version of Java, did nothing.

### Behaviours
**Expected behaviour**: RHRE loads the remix like normal

**Actual behaviour**: RHRE crashes

## Steps to reproduce issue
1. Open a big remix

**Comment by chrislo27** [comment]
Hi, according to your log file you are using Java 8u251 **32-bit**. Please uninstall Java and reinstall it from [here](https://java.com/en/download/manual.jsp). Make sure you select "Windows Offline (64-bit)". To uninstall, go to the Start Menu > Add or remove programs > And find Java in the list.

In the future there will be an in-program warning regarding 32-bit versions.

Please let me know if following my instructions above resolves the issue.

**Comment by RushKoopa** [comment]
Uninstalling and reinstalling worked, thanks!
