### ISSUE TITLE
RHRE Wont Load my Remix, and keeps Crashing.

### ISSUE THREAD

**Issue by TheEmeraldCreeperRB** [chrislo27/RhythmHeavenRemixEditor#325]
Because i am not able to Describe the Problem Exactly, I Have recorded a Video and Uploaded it to Youtube. Please watch it and Tell me what you are Able to do. (Video May not be completely uploaded).
https://www.youtube.com/watch?v=bIR94vCy9xQ&feature=youtu.be

EDIT: The video has been deleted because it took too long to upload. I'll Give the link when a new one is ready.

**Comment by chrislo27** [comment]
Closed due to insufficient information.
