### ISSUE TITLE
RHRE v3.20.2 Crashes when closing the "Open Remix" file selection.

### ISSUE THREAD

**Issue by oofiederp** [chrislo27/RhythmHeavenRemixEditor#326]
### Information
**Log file**: 
[log_2020-07-04_15-41-29.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4873821/log_2020-07-04_15-41-29.txt)

**Editor version**: RHRE v3.20.2
### Description
When attempting to close the file selection for opening up a remix, RHRE just crashes instead of going back to the editor.

### Behaviours
**Expected behaviour**: RHRE goes back to the editor with no new remix loaded.

**Actual behaviour**: RHRE crashes upon clicking the "X" in the file selection.

## Steps to reproduce issue
1. Click the "Open Remix" icon.
2. Do not select a remix, and instead close out of the file selection.
3. Instead of going back to the editor, it should instead crash, forcing one to have to reload the editor.

**Comment by chrislo27** [comment]
Cannot reproduce the error. The log file does not have any traces of an error occurring.

**Comment by chrislo27** [comment]
Closed due to inactivity. Feel free to reopen the issue if the problem is reproducible with steps.
