### ISSUE TITLE
RHRE v3.20.2 Crashes when opening Quiz show (Endless) after the fake crash.

### ISSUE THREAD

**Issue by FcoGMR17** [chrislo27/RhythmHeavenRemixEditor#327]
### Information
**Log file**: [log_2020-07-08_18-12-18.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4893574/log_2020-07-08_18-12-18.txt)

**Editor version**: RHRE v3.20.2

### Description
RHRE crashed when I tried to re-enter Quiz Show (Endless) after I spammed the buttons to fake crash RHRE.

### Behaviours
**Expected behaviour**: Re-open the Endless Mini-game

**Actual behaviour**: Crashes when trying to re-open it

## Steps to reproduce issue
1. Go into the "Extra" section of the "Info and Options" menu.
2. Open "Quiz Show" and get the fake crash by inputting more than 99 inputs.
3. Re-open "Quiz Show"
4. Instead of re-opening the mini-game, the editor crashes.

**Comment by chrislo27** [comment]
Fixed as of commit b369de2d20631831a71999da2501e90e27112345. This fix will be published in the next bugfix update. Thank you for the report!
