### ISSUE TITLE
It won't open at all.

### ISSUE THREAD

**Issue by KalebAdvent** [chrislo27/RhythmHeavenRemixEditor#328]
### Information
**Log file**: Doesn't exist yet.

**Editor version**: 3.20.2

### Description
When I open the run_windows file, nothing seems to happen.

### Behaviours
**Expected behaviour**: The program would open like normal.

**Actual behaviour**: The system32 window shows up with this text:

![image](https://user-images.githubusercontent.com/68093917/87114789-54794180-c226-11ea-8389-eb33f88c6671.png)

When I press a key, the window closes and nothing else happens.

**Comment by chrislo27** [comment]
Please ensure that you have [all of the requirements](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) per the front page README.

In this case please install Java 64-bit.

**Comment by KalebAdvent** [comment]
I had a feeling that's what it was. I thought I had Java already, but it must have been the 32-bit version.
