### ISSUE TITLE
"The system couldn't locate java.exe"

### ISSUE THREAD

**Issue by BobTheNerd10** [chrislo27/RhythmHeavenRemixEditor#329]
### Information
**Log file**: The program did not output a log file when run_windows.bat was opened, even with Java installed.

**Editor version**: RHRE_v3.20.2

### Description
When run_windows.bat is opened, the program proceeds to not open the editor and instead output this message.
"C:\Users\CENSORED\Downloads\Rhythm Heaven Remix Editor>java -jar -Xmx1024m bin/RHRE.jar
The system cannot find the file C:\ProgramData\Oracle\Java\javapath\java.exe.

C:\Users\CENSORED\Downloads\Rhythm Heaven Remix Editor>pause
Press any key to continue . . ." Even when reinstalling java, this issue still occurs. (I replaced my username with CENSORED because I do not want my real name online.)

### Behaviours
**Expected behaviour**: run_windows.bat is supposed to open the remix editor

**Actual behaviour**: run_windows.bat is not able to locate java.exe despite the fact that I have installed java

**Comment by chrislo27** [comment]
This is not an issue pertaining to RHRE. Please uninstall and reinstall Java 8, 64-bit. You can find more help related to the javapath folder with a search engine.
