### ISSUE TITLE
Heap Space Crash

### ISSUE THREAD

**Issue by bruhaps** [chrislo27/RhythmHeavenRemixEditor#330]
### Information
**Log file**: 
[log_2020-07-25_15-23-10.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4976482/log_2020-07-25_15-23-10.txt)

**Editor version**: 
3.20.2

### Description
When i try to open one of my remixes it crashes and says this 
![image](https://user-images.githubusercontent.com/68791868/88466268-30f20000-ce90-11ea-9e10-49945517544d.png)

### Behaviours
**Expected behaviour**: 
It is supposed to load the remix normally

**Actual behaviour**: 
It crashes and shows the crash screen above

## Steps to reproduce issue
1. I load the remix from the recover crashed remix screen or normally
2. It loads the remix
3. It either crashes when i try loading it or i can get in but it crashes a few seconds later

**Comment by chrislo27** [comment]
From looking through your log file, you have quite a lot of sounds loaded. However, I note that the log file indicates you only have around 930 MB of JVM memory available. That may not be enough to load all the sounds you want in memory.

How much RAM (memory) do you have on your computer? To check, you can open Task Manager (Ctrl+Shift+Esc), click More Details if it isn't already in full detail mode, and navigate to the Performance tab.

You should also consider increasing the amount of memory allocated to the program by editing the `run_windows.bat` file in a text editor. You can find out more [using this documentation page](https://rhre.readthedocs.io/en/latest/Out-of-memory-on-music/). However, do note that the amount of memory on your computer will determine how much you can allocate to RHRE.

**Comment by bruhaps** [comment]
i have 4.0 GB of ram, and using that documentation page helped, and it seems to be working normally, and without crashes.
