### ISSUE TITLE
RHRE v3.20.2 launcher doesn't launch on macOS Mojave

### ISSUE THREAD

**Issue by eggman199** [chrislo27/RhythmHeavenRemixEditor#331]
### Information
**Log file**: Did not generate a log file, since RHRE never opened. Instead, here's my Terminal output: 

Last login: Mon Jul 27 23:02:02 on ttys001
LAPTOP:~ USERNAME$ /Users/USERNAME/Downloads/Rhythm\ Heaven\ Remix\ Editor/run_macOS.command ; exit;
-bash: /Users/USERNAME/Downloads/Rhythm Heaven Remix Editor/run_macOS.command: /bin/zsh^M: bad interpreter: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Editor version**: RHRE v3.20.2 (laptop running macOS Mojave 10.14.6)

### Description
Running the "run_macOS.command" file to launch RHRE v3.20.x does not work. I get an error message in Terminal, and that's it. Versions 3.19 and down run fine.

### Behaviours
**Expected behaviour**: RHRE would open.

**Actual behaviour**: I got an error message from Terminal saying there was no such directory.

## Steps to reproduce issue
1. Download the latest release of RHRE v3.20.2.
2. Extract the zip into the Downloads folder.
3. Right-click on "run_macOS.command" and hit Open.

**Comment by chrislo27** [comment]
[Please switch your default shell to `zsh`.](https://scriptingosx.com/2019/06/moving-to-zsh/)

**Comment by eggman199** [comment]
I have switched the default shell to zsh but still recieve the same error message in Terminal.

**Comment by chrislo27** [comment]
Please try using the .command file attached below (unzip the zip file). Looks like there are DOS endings in the macOS launcher script even thought I thought I resolved that. If so this will be fixed for the next version.

[new_macos_cmd.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/4985804/new_macos_cmd.zip)

**Comment by eggman199** [comment]
This works! Thank you so much.
