### ISSUE TITLE
Program Runs, but there appears to be an issue everytime i boot it up

### ISSUE THREAD

**Issue by Avriel-Mimiga** [chrislo27/RhythmHeavenRemixEditor#334]
ok, now i have the right program, but it says theres an issue everytime it boots up

**Comment by Avriel-Mimiga** [comment]
![helk](https://user-images.githubusercontent.com/68927759/88741344-0c528e00-d105-11ea-9a94-c629a6c37c9b.PNG)
like this for example

**Comment by chrislo27** [comment]
Hi, please do not make unnecessary issues, such as #333. 

Please reply and upload the log file. You can find the logs folder at `C;/Users/<your user>/.rhre3/logs/`. If you cannot see the .rhre3 folder, enable viewing of hidden folders (you may look up how to do that).

Please also respect the project's [issue template](https://github.com/chrislo27/RhythmHeavenRemixEditor/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md) in the future.

**Comment by chrislo27** [comment]
Closed due to inactivity. Reopen the issue if you can reply and upload the log file.
