### ISSUE TITLE
Unable to switch audio outputs (but libgdx audio works)

### ISSUE THREAD

**Issue by Dylstructor** [chrislo27/RhythmHeavenRemixEditor#337]
### Information
Latest release
Playing on  Pop Os. 19.10
I open the app using start-linux.sh in the command line: (sh ./start-linux.sh) also tried (sudo sh ./startlinux.sh)
There is audio on the menu buttons/credits but not the actual SFX of the games :cry: 
As you can tell from the log. I opened a remix. And then i couldnt hear the sound of any of the games :(
Sounds do exist at home/mylinuxname/.rhre/sfx/master
### Log
[log_2020-09-06_13-06-41.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/5180079/log_2020-09-06_13-06-41.txt)

**Comment by chrislo27** [comment]
Thanks for the report. I have never used Pop!_OS before but from the log, it looks like the program defaulted to the mixer on your computer named "PCH [default]". I don't know what that is specifically, but you should check if it is outputting correctly. I don't know how related this [askubuntu](https://askubuntu.com/questions/278503/no-sound-with-hda-intel-pch) question is but it may be of some help.

**Comment by Dylstructor** [comment]
> Thanks for the report. I have never used Pop!_OS before but from the log, it looks like the program defaulted to the mixer on your computer named "PCH [default]". I don't know what that is specifically, but you should check if it is outputting correctly. I don't know how related this [askubuntu](https://askubuntu.com/questions/278503/no-sound-with-hda-intel-pch) question is but it may be of some help.

Why do all other sounds work though?

**Comment by chrislo27** [comment]
This may be a bug. However, in order to stay on the problem at hand (all sounds not outputting), please confirm that you have adjusted the PCH mixer to output correctly.

**Comment by Dylstructor** [comment]
oops didnt mean to close sorry

**Comment by Dylstructor** [comment]
yes i will do that in a second

**Comment by Dylstructor** [comment]
![image](https://user-images.githubusercontent.com/38115495/92332757-bfd46980-f045-11ea-96f5-c3ced9ffc990.png)
So its supposed to have this on the bottom correct?

**Comment by chrislo27** [comment]
I am not familiar enough with that to be able to give advice, sorry.

I am going to classify this as a bug with the program now because we should be able to switch audio outputs for the main program in the settings.

As for your question with why other audio works: libgdx rolls its own wrapper for OpenAL which is not appropriate for RHRE (we need to be able to export audio and apply filters to it). I use the Beads sound system for this but it is a bit old.

**Comment by Dylstructor** [comment]
> I am not familiar enough with that to be able to give advice, sorry.
> 
> I am going to classify this as a bug with the program now because we should be able to switch audio outputs for the main program in the settings.
> 
> As for your question with why other audio works: libgdx rolls its own wrapper for OpenAL which is not appropriate for RHRE (we need to be able to export audio and apply filters to it). I use the Beads sound system for this but it is a bit old.

BTW i just added that thing at the bottom of that file and it still doesn't work. It would be cool if there was a drop down asking what audio device you would like to use in the settings :+1:

**Comment by Dylstructor** [comment]
I know this is'int the repository for bouncy road mania but the same problem is also on there.

**Comment by Dylstructor** [comment]
Hello. I am sorry to bug you but it seems as you are updating the repository. Are you fixing the bug?

**Comment by chrislo27** [comment]
Hi, as of August 16th the project is no longer in active development. I was just updating some dependencies for security reasons, but I cannot give an ETA on when this issue will be fixed. 

That being said, I've been told that on Linux you can move audio streams between devices from your audioserver manager, can you look into that? Due to how the system works, it should be opening two audio streams on your audioserver (one from libgdx and one from Beads), one of them on the correct device, and the other on the incorrect one, so move the latter. (I don't have a tutorial on this so this is from me asking a colleague.)

**Comment by Dylstructor** [comment]
Seems to make sense. I will attempt to do this :+1:

**Comment by Dylstructor** [comment]
![image](https://user-images.githubusercontent.com/38115495/92422440-0b207200-f143-11ea-9d63-dc0b631504d2.png)
Hey! I just checked my pulse audio volume control. it seems as there is just one thing attempting to output audio "java"
There is not way for me to change what output device it is using :thinking:

**Comment by Dylstructor** [comment]
Oh. I figured it out. I seem to only have 1 audio device. How is the program attempting to select another audio device if i only have one? This seems really strange!

**Comment by chrislo27** [comment]
Hi @Dylstructor, please try this snapshot version. [Download it here](https://github.com/chrislo27/RHRE-snapshots/releases/tag/v3.20.4-SNAPSHOT_20200914). Open the Info and Settings menu in the top right and try selecting audio mixers and clicking the Test button to play test sounds through those mixers. When/if you find a working mixer, try using the editor normally. Also close and reopen RHRE to ensure that the settings are persisted correctly.

Please let me know your results.

**Comment by Dylstructor** [comment]
> Hi @Dylstructor, please try this snapshot version. [Download it here](https://github.com/chrislo27/RHRE-snapshots/releases/tag/v3.20.4-SNAPSHOT_20200914). Open the Info and Settings menu in the top right and try selecting audio mixers and clicking the Test button to play test sounds through those mixers. When/if you find a working mixer, try using the editor normally. Also close and reopen RHRE to ensure that the settings are persisted correctly.
> 
> Please let me know your results.
> 
> ![image](https://user-images.githubusercontent.com/6299069/93168239-3cff7e80-f6d7-11ea-928a-4ff8736c367a.png)

Hey!. Thank you so much for all the help. It seems to finally work! You are really quite an amazing developer. I am finally going to be able to start a project of mine! Thanks again!

**Comment by chrislo27** [comment]
Glad to hear it works. You can continue to use the snapshot until the next patch version, v3.20.4, is released — that may be a few weeks away. Thank you for your report!

**Comment by chrislo27** [comment]
Closed with the release of [v3.20.4](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.20.4).
