### ISSUE TITLE
Can't open Editor

### ISSUE THREAD

**Issue by Yanlvc** [chrislo27/RhythmHeavenRemixEditor#339]
### Information
**Log file**: GFLW_API_UNAVAILEABLE

**Editor version**: 3.20.3

### Description
The editor doest open and It keeps giving errors.

### Behaviours
**Expected behaviour**: It was supposed to Run the editor

**Actual behaviour**: 
![image](https://user-images.githubusercontent.com/71611451/93723038-9a7d4a80-fb71-11ea-9e11-73a2d897d770.png)

## Steps to reproduce issue
1. Download the editor
2. Open editor
3. There's no step 3

**Comment by chrislo27** [comment]
As per the [program requirements](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements), your graphics driver does not support GLFW (and thus OpenGL). You can try updating your graphics drivers. This is not a problem with RHRE so the issue will be closed.

**Comment by Yanlvc** [comment]
Oh.Thats sad
