### ISSUE TITLE
Not able to load .command file

### ISSUE THREAD

**Issue by thatgeoHacker** [chrislo27/RhythmHeavenRemixEditor#340]
I've been getting this problem every time i try to run the latest update (3.20.3). It says when i try to open it, "The file "run_macOS.command" could not be executed because you do not have appropriate access privileges." below it says, "To view or change access privileges, select the file in the Finder and choose File > Get info." but every time i try to change the privileges, it still doesn't work, is there a way to fix this? (Image below to help.)
<img width="420" alt="Screenshot 2020-09-25 at 17 44 30" src="https://user-images.githubusercontent.com/71895426/94293932-f0c60100-ff56-11ea-9523-86cefa5d3ade.png">

**Comment by chrislo27** [comment]
Hi, [as of 2020-08-14, macOS is not a supported OS for RHRE](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) so I cannot help you with your issue.
