### ISSUE TITLE
File choosers do not load on 32-bit Java as of v3.20.4

### ISSUE THREAD

**Issue by RebatemanYT** [chrislo27/RhythmHeavenRemixEditor#342]
### Information
Log: Don't have it here, most likely wouldn't help anyway. (deleted to reinstall)

**Editor version**: v3.20.4/.3

### Description
So in .3, I found out that it didn't finish the update so I decided to just redownload, where when I try to save or load a remix, the file explorer didn't pop up.

### Behaviours

No File Explorer
**Expected behaviour**: Open Remix, goes into the Open Remix menu, have a file explorer open.

**Actual behaviour**: Open Remix, goes into the Open Remix menu, doesn't open anything, leading me to need to close the program.

Can't Directly Update
**Expected behaviour**: Open the program, choose to update from .3 to .4, finishes eventually.

**Actual behaviour**: Open the program, choose to update from .3 to .4, after a bit won't update,

## Steps to reproduce issue

No File Explorer
1. Install via the zip file the program's 3.20.4 version (may need to have either have put source code version or the previous version already in folder or sub folder).
2. Open the program (either via batch or java, on windows).
3. Press Open Remix (or Save Remix, may also be with Music but may not be because button)
4. If no file explorer opens, you have my problem too.

Can't Directly Update
1. Open RHRE on v3.20.3.
2. Choose to update the program.
3. Wait (don't know actual time it takes, was just on the side for me).
4. If it says it couldn't update, you have my problem too.

**Comment by chrislo27** [comment]
Hi, without any log files I cannot help you. Please manually download the latest update [here](https://github.com/chrislo27/RhythmHeavenRemixEditor/releases/tag/v3.20.4).

**Comment by RebatemanYT** [comment]
i did manually update the game but that was I think the problem that happened to make the problem with no file explorer.

**Comment by RebatemanYT** [comment]
also i don't think i get a log.

**Comment by RebatemanYT** [comment]
i can't automatically update but when i manually update the program doesn't work. I guess that the problem is involving the removal or addition of a file or line of code.

**Comment by RebatemanYT** [comment]
Ok, I have found a workaround to not receiving a log. I have recorded it with the command prompt shown and desktop (with RHRE open) shown separately. Here is the video link on YT (public btw) - https://youtu.be/0BpaY3xbiCA (most likely will be uploaded by the time you see this). In the video you can see...
1. There is no log file that appears.
2. There are a few errors in the command prompt.
3. Nothing happens when I enter the Open Remix menu other than it opening (no file explorer).
Please fix the errors.

**Comment by chrislo27** [comment]
Your video is too low-resolution for me to make out any words, sorry. Please follow the instructions below to upload a log file.

You can find your log file(s) in this folder: `C:/Users/<your user name>/.rhre3/logs/`. If you don't see the `.rhre3` folder, you may have to enable viewing of hidden files and folders. To do that, open File Explorer > View tab > Make sure that "File name extensions" and "Hidden items" are checked.

![image](https://user-images.githubusercontent.com/6299069/94625464-a8b42080-026d-11eb-8a89-f71920896652.png)

Please note that they are timestamped with the date and time of when the program was run in the filename. For best results, run RHRE, reproduce the problem, close RHRE, and then use the most recently created log file.

![image](https://user-images.githubusercontent.com/6299069/94625633-12ccc580-026e-11eb-8301-f997762c8e1c.png)

To upload it, drag and drop it into the comment box here on GitHub. That way I can see it and read the error log.

By the way, the bugfix for the file explorer in the last update is not related to this; this seems like a new problem.

Thanks for your patience and cooperation!

**Comment by chrislo27** [comment]
Please also note that I do not generally provide support for users running 32-bit Java, so please update to a 64-bit version at your earliest convenience. You can do so [from here](https://java.com/en/download/manual.jsp), make sure to close RHRE first, select and download Windows Offline (64-bit), and run the installer.

**Comment by RebatemanYT** [comment]
Thanks, I actually thought the log files were meant to be in the same folder as the remix editor. Also I haven't gotten the 64 bit version yet because of space and others using the internet. I am downloading it rn (as rn i am the only one here physically) but here is the log file from that time in the recording. Hope it helps. Still, I will also copy-paste the end bit of the log just in case if the log upload doesn't work.
00:00:30.921: [DEBUG][main] Changed screens from io.github.chrislo27.rhre3.screen.SFXDBLoadingScreen to io.github.chrislo27.rhre3.screen.EditorScreen
00:00:37.492: [DEBUG][main] Changed screens from io.github.chrislo27.rhre3.screen.EditorScreen to io.github.chrislo27.rhre3.screen.OpenRemixScreen
Exception in thread "DefaultDispatcher-worker-3" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl_tinyfd.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.util.tinyfd.TinyFileDialogs.<clinit>(TinyFileDialogs.java:37)
	at io.github.chrislo27.rhre3.util.TinyFDWrapper.openFile(TinyFDWrapper.kt:37)
	at io.github.chrislo27.rhre3.util.TinyFDWrapper.openFile(TinyFDWrapper.kt:45)
	at io.github.chrislo27.rhre3.screen.OpenRemixScreen$openPicker$1.invokeSuspend(OpenRemixScreen.kt:297)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[Controllers] removed manager for application, 0 managers active
00:01:06.532: [INFO][main] Starting dispose call
00:01:06.560: [INFO][main] Dispose call finished, goodbye!
00:01:06.576: [INFO][main] Persisting window settings as 1366x715
and that is the end of it. Still, hope the 64 bit helps me out on not just RHRE but also other programs. Also hope you are ok.
[log_2020-09-30_11-16-56.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/5302352/log_2020-09-30_11-16-56.txt)

**Comment by chrislo27** [comment]
Awesome, thank you for the log.

I have narrowed down the error to... well, 32-bit-ness. I would advise you to try running RHRE and opening the file chooser once you install the 64-bit version of Java -- you can verify this if the 32-bit warning doesn't show up.

Technical reason:  
The file chooser provider by LWJGL3, tinyfd, split off its code files into separate 32-bit ("x86") and 64-bit ("x64") versions.  Previously they were combined. I've resolved the problem for the next patch, v3.20.5. That may come out as early as later today since I have another important fix on it.

As for your auto-updater problem: I don't know the root cause but there is a connection error in your log file. Again, I don't know if updating Java could fix that. The auto-updater is a convenience, but if it does not work as you expect, you can always download the latest update manually. (RHRE was originally designed without an auto-updater, the auto-updater is a relatively recent addition).

Thanks for your bug report! I hope this helped.
