### ISSUE TITLE
Add Seika Relay

### ISSUE THREAD

**Issue by siky112** [chrislo27/RhythmHeavenRemixEditor#343]
### Information
**Editor version**: Should not matter

**SFX Database version**: v122

### Description
Seika Relay, also known as Torch Relay, is an unused endless minigame, much like the unused introduction in _Tengoku_. You have to press A and B every two beats. It was never finished, but there is still some gameplay. For more info, see https://rhythmheaven.fandom.com/wiki/Seika_Relay.

**Comment by siky112** [comment]
wow that was fast

**Comment by chrislo27** [comment]
After discussion with other knowledgable members of the community, the only SFX used in Torch Relay is the Monkey Watch clap. Therefore, if you want to use the Torch Relay SFX, you can use the Monkey Watch clap. Implementing an entire SFX Database game for it will have marginal benefits at best, so this will not be pursued further.
