### ISSUE TITLE
"Missing Files" when updating 

### ISSUE THREAD

**Issue by meezypeezy** [chrislo27/RhythmHeavenRemixEditor#344]
### Information
**Log file**: [My Log File (BUG).txt](https://github.com/chrislo27/RhythmHeavenRemixEditor/files/5328224/My.Log.File.BUG.txt)

**Editor version**: 3.20.5

### Description
It says it was "Missing Files" when it was updating the SFX Database, while I think it had all the files stored. Why does this happen?

### Behaviours
**Expected behaviour**: Log into RHRE like normal and begin remixing.

**Actual behaviour**: It said there was "Missing Files" when it was updating the SFX database...

![Screenshot (24)](https://user-images.githubusercontent.com/72401075/95097848-f3191f80-06fb-11eb-8398-211cb8e0b696.png)

**Comment by chrislo27** [comment]
Hi, thanks for your report.

From your log file, it looks like your connection was interrupted mid-way through the SFX DB updating process. You should try launching the program again to see if the error returns. If it does, you may have to force the program to re-fetch the DB:
1. Go to `C:/Users/<your user>/.rhre3/` in File Explorer.
2. Select the `sfx` directory and delete it.
3. Relaunch RHRE.

**Comment by meezypeezy** [comment]
> Hi, thanks for your report.
> 
> From your log file, it looks like your connection was interrupted mid-way through the SFX DB updating process. You should try launching the program again to see if the error returns. If it does, you may have to force the program to re-fetch the DB:
> 
> 1. Go to `C:/Users/<your user>/.rhre3/` in File Explorer.
> 2. Select the `sfx` directory and delete it.
> 3. Relaunch RHRE.

I reopened it and it didn't work, however I'll try the second strategy to see of that appears.

**Comment by meezypeezy** [comment]
Looks like your helpings worked! I think I used custom sound effects on a custom remix, however they were lost when I was a few steps through.

I feel like the SFX file updates but causes the crash. Thanks for your help! Closing.
