### ISSUE TITLE
Not an bug,But a question

### ISSUE THREAD

**Issue by Yanlvc** [chrislo27/RhythmHeavenRemixEditor#345]
I'm back  with a new pc,And i redownloaded the editor trying to use it.Can anyone tell me how to open it ? or tell me if i have the requirements? 
![image](https://user-images.githubusercontent.com/71611451/95940007-bca26b00-0db3-11eb-9db7-3ffa6ec003d2.png)

64 BITS pc
Edit : Jar file error included

**Comment by chrislo27** [comment]
Please view the [Requirements](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) and [Installation](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation) sections on the front page. The Issues section is for reporting bugs.
