### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by SomebodyhereIguess** [chrislo27/RhythmHeavenRemixEditor#346]
"C:\Users\notgonnashowusernamesection\Downloads\RHRE_v3.20.5\Rhythm Heaven Remix Editor>java -jar -Xmx1024m bin/RHRE.jar
'java' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\notgonnashowusernamesection\Downloads\RHRE_v3.20.5\Rhythm Heaven Remix Editor>pause
Press any key to continue . . ."
thats all that appears when i do what im told to do to launch it

**Comment by chrislo27** [comment]
Please ensure you have all the [requirements](https://github.com/chrislo27/RhythmHeavenRemixEditor#requirements) and that you follow the [installation steps](https://github.com/chrislo27/RhythmHeavenRemixEditor#installation).
